import { test, expect, type Page } from '@playwright/test';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { root,evidence,phase,login,capture,route,jsonAPI } from './phase4-support';

async function exactDownload(page:Page,button:string,name:string){const waiting=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const downloaded=await waiting;const file=await downloaded.path();expect(file).toBeTruthy();const raw=await readFile(file!,'utf8');await writeFile(path.join(evidence,name+'.json'),raw);return raw;}
async function hoverPrecise(page:Page){const image=page.getByRole('img',{name:/测点历史趋势/}).first();const box=(await image.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await expect(page.locator('.sf-chart-tooltip:visible').first()).toContainText('9007199254740993');const tooltip=await page.locator('.sf-chart-tooltip:visible').first().innerText();expect(tooltip).toContain('precision-source');expect(tooltip).toContain('count');return tooltip;}

test('cloud and edge real charts tables and complete export preserve every numeric representation',async({browser})=>{
  test.skip(phase!=='precision');const results=[];
  for(const kind of ['cloud','edge']){const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();await login(page,kind,kind==='edge'?'edge.html':'index.html','admin');const fixture=JSON.parse(await readFile(path.join(root,kind+'-precision','precision-manifest.json'),'utf8'));await route(page,'data?device='+encodeURIComponent(fixture.device));await page.getByLabel('测点名称').fill('precise_integer');await expect(page.getByText('9007199254740993',{exact:true})).toBeVisible();const tooltip=await hoverPrecise(page);await capture(page,kind+'-precise-tooltip');await page.getByLabel('测点名称').fill(Object.keys(Object.fromEntries(fixture.points.map((point:any)=>[point.key,true]))).join(','));const table=page.locator('.ant-card').filter({has:page.getByText('精确观测记录',{exact:true})});await expect(table).toContainText('18446744073709551615');await expect(table).toContainText('-9007199254740993');await expect(table).toContainText('12.345678901234567');await expect(table).toContainText('true');const raw=await exactDownload(page,'导出完整精确数据',kind+'-exact-export');expect(raw).toMatch(/"value":\s*9007199254740993/);expect(raw).toMatch(/"value":\s*"9007199254740993"/);expect(raw).toContain('18446744073709551615');expect(raw).toContain('-9007199254740993');expect(raw).toContain('12.345678901234567');expect(raw).toMatch(/"average":\s*9007199254740993/);await capture(page,kind+'-precise-table-export');results.push({kind,tooltip,export_bytes:Buffer.byteLength(raw),unsafe_integer:'9007199254740993',unsigned_integer:'18446744073709551615',row_count:JSON.parse(raw).items.length});await context.close();}
  await writeFile(path.join(evidence,'exact-values-browser.json'),JSON.stringify(results,null,2));
});

test('screen metric details tooltip and complete export preserve precise observation',async({page})=>{
  test.skip(phase!=='precision');await login(page,'cloud','screen.html','admin');const manifest=JSON.parse(await readFile(path.join(root,'cloud-precision','precision-manifest.json'),'utf8'));const entities=JSON.parse((await jsonAPI(page,'/entities')).text);const name=entities.find((entity:any)=>entity.id===manifest.device).name;await page.getByRole('button',{name:'配置大屏',exact:true}).click();const modal=page.getByRole('dialog',{name:'配置运行大屏'});while(await modal.getByRole('button',{name:'删除',exact:true}).count())await modal.getByRole('button',{name:'删除',exact:true}).first().click();await modal.getByRole('button',{name:'添加指标',exact:true}).click();await modal.getByLabel('指标 1 的设备').click();await modal.getByLabel('指标 1 的设备').press('Home');for(let step=0;step<30;step++){const active=page.locator('.ant-select-dropdown:visible .ant-select-item-option-active .ant-select-item-option-content');if(await active.count()&&(await active.innerText())===name){await modal.getByLabel('指标 1 的设备').press('Enter');break;}await modal.getByLabel('指标 1 的设备').press('ArrowDown');}await modal.getByLabel('指标 1 的测点').fill('precise_integer');await modal.getByLabel('指标 1 的标题').fill('精确累计指标');await modal.getByRole('button',{name:'保存大屏',exact:true}).click();await expect(modal).toBeHidden();const metric=page.getByRole('button',{name:/精确累计指标/});await expect(metric).toContainText('9007199254740993');await metric.click();const drawer=page.getByRole('dialog',{name:'精确累计指标'});await expect(drawer.getByText('9007199254740993',{exact:true})).toBeVisible();await drawer.getByRole('img',{name:/测点历史趋势/}).scrollIntoViewIfNeeded();await page.waitForTimeout(250);const box=(await drawer.getByRole('img',{name:/测点历史趋势/}).boundingBox())!;await page.mouse.move(box.x+box.width/2+20,box.y+box.height/2);await expect(drawer.locator('.sf-chart-tooltip:visible')).toContainText('9007199254740993');await capture(page,'screen-exact-detail-tooltip');await drawer.getByRole('button',{name:'关闭',exact:true}).click();const raw=await exactDownload(page,'导出精确大屏数据','screen-exact-export');expect(raw).toMatch(/"value":\s*9007199254740993/);expect(raw).toContain('18446744073709551615');await capture(page,'screen-exact-metric-export');
});

test('actual subscription passes a heartbeat new commit and opaque cursor reconnection',async({page,context})=>{
  test.skip(phase!=='precision');await login(page,'cloud','index.html','admin');await route(page,'alarm-workbench');await page.getByLabel('页面刷新方式').click();await page.locator('.ant-select-dropdown:visible').getByText('实时推送',{exact:true}).click();await expect(page.getByText('订阅已连接',{exact:true})).toBeVisible();const reconnects:string[]=[];page.on('request',request=>{if(request.url().endsWith('/queries/alarms/events'))reconnects.push(request.headers()['last-event-id']||'');});await context.setOffline(true);await expect(page.getByText('等待网络恢复',{exact:true})).toBeVisible();await page.waitForTimeout(1200);await context.setOffline(false);await expect.poll(()=>reconnects.some(cursor=>cursor.length>10)).toBe(true);await expect(page.getByText('订阅已连接',{exact:true})).toBeVisible();
  const scope={resource_ids:['agv-1'],keys:['heartbeat_precision'],from_ms:Date.now()-3600000,to_ms:Date.now()+60000,limit:20};const result=await page.evaluate(async scope=>{const token=sessionStorage.getItem('smartfactory.session.'+location.host);const headers={'Content-Type':'application/json',Authorization:'Bearer '+token};const controller=new AbortController();const response=await fetch('/api/sf/v1/queries/trend/events',{method:'POST',headers,body:JSON.stringify(scope),signal:controller.signal});const reader=response.body!.getReader();const decoder=new TextDecoder();let buffer='';const frames:string[]=[];let cursor='';let heartbeat=false;let delta=false;let submitted=false;const start=Date.now();try{while(Date.now()-start<23000){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});let end;while((end=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,end);buffer=buffer.slice(end+2);frames.push(frame);const id=frame.split('\n').find(line=>line.startsWith('id:'));if(id)cursor=id.slice(3).trim();if(frame.startsWith(':'))heartbeat=true;const data=frame.split('\n').find(line=>line.startsWith('data:'));if(data&&JSON.parse(data.slice(5)).type==='delta')delta=true;}if(heartbeat&&!submitted){submitted=true;const at=Date.now();await fetch('/api/sf/v1/ingest',{method:'POST',headers,body:JSON.stringify({message_id:'heartbeat-'+at,source_id:'precision-source',payload_hash:'',critical:false,points:[{id:'heartbeat-'+at,message_id:'heartbeat-'+at,source_id:'precision-source',device_id:'agv-1',key:'heartbeat_precision',value:42,observed_ms:at,received_ms:at,source_sequence:at,revision:1,quality:'GOOD'}]})});}if(heartbeat&&delta)break;}}finally{controller.abort();}const resumed=new AbortController();const resume=await fetch('/api/sf/v1/queries/trend/events',{method:'POST',headers:{...headers,'Last-Event-ID':cursor},body:JSON.stringify(scope),signal:resumed.signal});const resumeReader=resume.body!.getReader();const first=await resumeReader.read();const firstFrame=new TextDecoder().decode(first.value);resumed.abort();return {status:response.status,elapsed_ms:Date.now()-start,heartbeat,delta,cursor,frames,resume_status:resume.status,resume_first_frame:firstFrame};},scope);
  expect(result.status).toBe(200);expect(result.heartbeat).toBe(true);expect(result.delta).toBe(true);expect(result.elapsed_ms).toBeGreaterThanOrEqual(14000);expect(result.resume_status).toBe(200);expect(result.cursor.length).toBeGreaterThan(10);await writeFile(path.join(evidence,'query-heartbeat-resume.json'),JSON.stringify({ui_reconnect_cursors:reconnects,...result},null,2));await capture(page,'query-offline-resume');
});
