import { test, expect, type Page } from '@playwright/test';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { root, evidence, phase, clean, login, capture, route, jsonAPI } from './phase4-support';

test('continuous sampling keeps reviewed alarm action and persistent operation',async({page})=>{test.skip(phase!=='business');await login(page);await route(page,'alarm-workbench');await page.getByRole('button',{name:'查看告警详情'}).first().click();await page.getByRole('button',{name:'确认告警',exact:true}).click();const dialog=page.getByRole('dialog',{name:'确认告警'});await dialog.getByLabel('处置理由',{exact:true}).fill('页面验证：持续采样期间保持已阅告警依据');const actionVersion=await dialog.locator('.reviewed-version code').innerText();await page.waitForTimeout(17000);const wait=page.waitForResponse(response=>response.request().method()==='POST'&&response.url().includes('/alarms/')&&response.url().endsWith('/actions'));await dialog.getByRole('button',{name:'提交处置'}).click();const response=await wait;expect(response.status()).toBe(200);const input=JSON.parse(response.request().postData()!);expect(input.expected_action_version).toBe(actionVersion);const result=await response.json();expect(result.case.acknowledged).toBe(true);expect(result.case.operations.at(-1).reason).toContain('页面验证');await writeFile(path.join(evidence,'alarm-persisted.json'),JSON.stringify(clean({input,result}),null,2));await capture(page,'alarm-continuous-confirmation');});

test('work order creation, handling and reviewed handover persist the complete workflow',async({page})=>{test.skip(phase!=='business');await login(page);const manifest=JSON.parse(await readFile(path.join(root,'cloud-'+(process.env.SF_PHASE4_DATA_SUFFIX||'first'),'manifest.json'),'utf8'));await route(page,'work-orders');await page.getByRole('button',{name:'创建工单',exact:true}).click();const dialog=page.getByRole('dialog',{name:'创建处理工单'});await dialog.getByLabel('工单标题').fill('页面流程：温度复查与交班');await dialog.getByLabel('处理内容').fill('核对温度传感器并保存交班依据');await dialog.getByLabel('关联告警身份',{exact:true}).fill(manifest.alarm_id);const createdResponse=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/work-orders'));await dialog.getByRole('button',{name:'保存工单'}).click();const created=await createdResponse;expect(created.status()).toBe(200);const detail=await created.json();await expect(page.getByRole('dialog',{name:'工单责任与交接记录'})).toBeVisible();await page.getByRole('button',{name:'开始处理',exact:true}).click();const start=page.getByRole('dialog',{name:'开始处理'});await start.getByLabel('工单变更理由').fill('现场开始复核');await start.getByRole('button',{name:'提交工单变更'}).click();await expect(start).toBeHidden();await page.getByRole('button',{name:'办理交接',exact:true}).click();const handover=page.getByRole('dialog',{name:'办理交接'});await handover.getByLabel('新的责任人身份').fill('operator-b');await handover.getByLabel('未完成事项').fill('下一班次复核温度曲线\n检查风机运行');await handover.getByLabel('工单变更理由').fill('由下一班次继续处理');await handover.getByRole('checkbox').first().check();const alarmChoice=handover.getByRole('checkbox').filter({hasText:'alarm'});await handover.getByLabel(new RegExp('alarm /')).check();const wait=page.waitForResponse(r=>r.url().endsWith('/handovers')&&r.request().method()==='POST');await handover.getByRole('button',{name:'提交工单变更'}).click();const handed=await wait;expect(handed.status()).toBe(200);const result=await handed.json();expect(result.work_order.assignee_id).toBe('operator-b');expect(result.handovers.at(-1).pending_items).toHaveLength(2);expect(result.handovers.at(-1).evidence.some((item:any)=>item.kind==='alarm'&&item.action_version)).toBe(true);await writeFile(path.join(evidence,'handover-persisted.json'),JSON.stringify(clean(result),null,2));await capture(page,'work-order-reviewed-handover');});

test('five templates bind pinned device and connector revisions then prepare twenty-five drafts',async({page})=>{test.skip(phase!=='business');await login(page);await route(page,'scene-templates');const ids=['温湿度与通风','红外照明','危气监测','AGV 避障','货物计数'];for(const name of ids){const card=page.locator('.definition-card,.ant-card').filter({has:page.getByText(name,{exact:true})}).first();await card.getByRole('button',{name:'使用此模板'}).click();await page.getByLabel('模板绑定设备').click();await page.getByLabel('模板绑定设备').press('ArrowDown');await page.getByLabel('模板绑定设备').press('Enter');await page.getByLabel('模板绑定配置').click();await page.getByLabel('模板绑定配置').press('ArrowDown');await page.getByLabel('模板绑定配置').press('Enter');await page.getByRole('button',{name:'加入待准备批次'}).click();}const wait=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/template-batches'));await page.getByRole('button',{name:'检查冲突并批量准备草稿'}).click();const response=await wait;expect(response.status()).toBe(200);const result=await response.json();expect(result.status).toBe('prepared');expect(result.drafts).toHaveLength(25);expect(result.bindings).toHaveLength(5);expect(result.input.instances.every((item:any)=>item.device_version&&item.configuration_version&&item.configuration_id)).toBe(true);await writeFile(path.join(evidence,'templates-persisted.json'),JSON.stringify(clean(result),null,2));await capture(page,'five-templates-prepared');});

test('edge metadata protocol form validates ranges and preserves extensions through save',async({page})=>{test.skip(phase!=='business');await login(page,'edge','edge.html');await route(page,'protocol-configurations');await page.getByLabel('参数设备').click();await page.locator('.ant-select-dropdown:visible .ant-select-item-option').first().click();await page.getByRole('button',{name:'编辑设备参数'}).click();await page.getByRole('tab',{name:'完整参数与扩展',exact:true}).click();const raw=page.getByLabel('完整协议参数');const value=JSON.parse(await raw.inputValue());value.address ??= {};value.address.extension_counter='9007199254740993';value.datapoints[0].extension_tag={keep:'前端往返'};await raw.fill(JSON.stringify(value,null,2));await page.getByRole('button',{name:'配置预检',exact:true}).click();await expect(page.getByText('配置预检通过',{exact:true})).toBeVisible();const wait=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/device-configurations'));await page.getByRole('button',{name:'保存参数',exact:true}).click();const response=await wait;expect(response.status()).toBe(200);const result=await response.json();expect(result.configuration.parameters.address.extension_counter).toBe('9007199254740993');expect(result.configuration.parameters.datapoints[0].extension_tag.keep).toBe('前端往返');await writeFile(path.join(evidence,'device-parameters-persisted.json'),JSON.stringify(clean(result),null,2));await capture(page,'protocol-metadata-roundtrip');});

test('canvas edits survive route changes and semantic review provides identity-bearing results',async({page})=>{test.skip(phase!=='business');await login(page);await route(page,'analysis');await page.locator('.draft-list button').first().click();const name=page.getByLabel('定义名称');await name.fill('未提交画布编辑：页面切换保留');await route(page,'runtime');await route(page,'analysis');await expect(name).toHaveValue('未提交画布编辑：页面切换保留');await page.getByRole('button',{name:'语义差异与影响',exact:true}).click();await expect(page.getByRole('dialog',{name:'草稿语义差异与影响'})).toBeVisible();await expect(page.getByText('草稿依据',{exact:true})).toBeVisible();await capture(page,'semantic-impact-and-retained-editor');});

test('cloud edge and screen charts adapt to three actual viewport sizes',async({browser})=>{test.skip(phase!=='surfaces');for(const [kind,surface] of [['cloud','index.html'],['edge','edge.html'],['cloud','screen.html']]){for(const [width,height]of[[1440,1000],[1024,768],[390,844]]){const context=await browser.newContext({viewport:{width,height}});const page=await context.newPage();await login(page,kind,surface,process.env.SF_PHASE4_SURFACE_USER||'operator-a');await expect(page.getByText('有效观测',{exact:true}).locator('..')).not.toHaveText(/有效观测\s*0\s/);await expect(page.getByRole('img',{name:/测点历史趋势/}).first()).toBeVisible();await expect(page.locator('canvas').first()).toBeVisible();await capture(page,`${kind}-${surface}-${width}x${height}`);await context.close();}}});
