import { test, expect, type Page } from '@playwright/test';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { root,evidence,phase,precisionCloud,login,instrument,capture,route,jsonAPI } from './phase4-support';

async function alarmAction(page:Page,id:string,action:string){const detail=JSON.parse((await jsonAPI(page,'/alarms/'+encodeURIComponent(id))).text);const result=await jsonAPI(page,'/alarms/'+encodeURIComponent(id)+'/actions',{request_id:crypto.randomUUID(),expected_version:detail.case.version,expected_action_version:detail.action_version,action,reason:'查询窗口竞争验证：'+action});expect(result.status).toBe(200);return JSON.parse(result.text);}
async function openModbus(page:Page){await login(page,'edge','edge.html');await route(page,'protocol-configurations');await page.getByLabel('参数设备').click();await page.locator('.ant-select-dropdown:visible').getByText('温湿度与通风',{exact:true}).click();await page.getByRole('button',{name:'编辑设备参数',exact:true}).click();return page.getByRole('dialog',{name:'设备基础参数编辑'});}

test('F01 delayed real HTTP snapshot cannot undo committed SSE update remove and return events',async({page})=>{
  test.skip(phase!=='state');await instrument(page);const credentials=JSON.parse(await readFile(path.join(root,'cloud-precision','private-credentials.json'),'utf8'));await page.addInitScript(()=>{const original=window.fetch;const frames:unknown[]=[];(window as any).__sfFrames=frames;window.fetch=async(...args)=>{const response=await original(...args);if(String(args[0]).endsWith('/events')){const reader=response.clone().body!.getReader();const decoder=new TextDecoder();void(async()=>{let pending='';try{for(;;){const chunk=await reader.read();if(chunk.done)break;pending+=decoder.decode(chunk.value,{stream:true});let end;while((end=pending.indexOf('\n\n'))>=0){const frame=pending.slice(0,end);pending=pending.slice(end+2);if(frames.length<500)frames.push({path:String(args[0]),scope:args[1]?.body,frame});}}}catch{}})();}return response;};});await page.goto(precisionCloud+'/index.html');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill(credentials.password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('button',{name:'退出',exact:true})).toBeVisible();
  const key='query_race_'+crypto.randomUUID().slice(0,8);const at=Date.now()-101*60000;
  const points=Array.from({length:100},(_,index)=>({id:key+'-'+index,device_id:'agv-1',key,value:index===0?81:181+index,observed_ms:at+index*60000,revision:1,quality:'GOOD'}));
  const ingest=async(values:typeof points)=>{const message='race-'+crypto.randomUUID();const result=await jsonAPI(page,'/ingest',{message_id:message,source_id:'precision-source',payload_hash:'',critical:false,points:values.map(point=>({...point,message_id:message,source_id:'precision-source',source_sequence:Date.now(),received_ms:Date.now()}))});expect(result.status).toBe(200);return JSON.parse(result.text);};await ingest(points);await route(page,'data?device=agv-1');await page.getByLabel('测点名称').fill(key);await page.getByLabel('页面刷新方式').click();await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText('实时推送',{exact:true}).click();
  let release!:()=>void;const wait=new Promise<void>(resolve=>{release=resolve;});let original:any;let held=false;let fulfilled=false;await page.route('**/api/sf/v1/queries/trend',async interception=>{const request=JSON.parse(interception.request().postData()||'{}');if(request.resolution!=='raw'||!request.keys?.includes(key)||request.from_ms>Date.now()-20*3600000){await interception.continue();return;}const response=await interception.fetch();original=await response.json();held=true;await wait;try{await interception.fulfill({response});fulfilled=true;}catch{}});
  await page.getByLabel('历史时间范围').click();await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText('最近24小时',{exact:true}).click();await page.getByRole('button',{name:'查询历史',exact:true}).click();await expect.poll(()=>held).toBe(true);const table=page.locator('.ant-card').filter({has:page.getByText('精确观测记录',{exact:true})}).locator('tbody .ant-table-row');await expect(table).toHaveCount(100);await expect(table.locator('code').getByText('81',{exact:true})).toHaveCount(1);
  const observed=[];observed.push(await ingest([{...points[99],value:9999,revision:2}]));await expect(table.locator('code').getByText('9999',{exact:true})).toHaveCount(1);observed.push(await ingest([{...points[99],id:key+'-new',observed_ms:at+100*60000,value:7777,revision:1}]));await expect(table).toHaveCount(100);await expect(table.locator('code').getByText('7777',{exact:true})).toHaveCount(1);await expect(table.locator('code').getByText('81',{exact:true})).toHaveCount(0);
  release();await page.waitForTimeout(1200);const values=await table.locator('code').allTextContents();const frames=await page.evaluate(()=>(window as any).__sfFrames);await writeFile(path.join(evidence,'F01-http-sse-snapshot-race.json'),JSON.stringify({key,original,observed,frames,http_response_fulfilled:fulfilled,visible_after_http:values},null,2));await capture(page,'F01-after-delayed-http');expect(values).toContain('9999');expect(values).toContain('7777');expect(values).not.toContain('81');await page.unroute('**/api/sf/v1/queries/trend');

});

test('F02 raw JSON repair clears previous metadata-field error',async({page})=>{
  test.skip(phase!=='state');const drawer=await openModbus(page);await drawer.getByRole('tab',{name:'设备地址',exact:true}).click();await drawer.getByLabel(/^设备从站地址/).fill('invalid');await drawer.getByRole('tab',{name:'完整参数与扩展',exact:true}).click();const raw=drawer.getByLabel('完整协议参数');const value=JSON.parse(await raw.inputValue());value.address??={};value.address.unit_id=1;await raw.fill(JSON.stringify(value,null,2));await drawer.getByRole('button',{name:'配置预检',exact:true}).click();await capture(page,'F02-raw-json-repair');await expect(drawer.getByText('配置预检通过',{exact:true})).toBeVisible();
});

test('F02 deleting invalid repeated metadata item removes its validation state',async({page})=>{
  test.skip(phase!=='state');const drawer=await openModbus(page);await drawer.getByRole('tab',{name:'数据点',exact:true}).click();await drawer.getByLabel(/^数据点 1：寄存器地址/).fill('invalid');await drawer.getByRole('button',{name:'删除数据点',exact:true}).first().click();await drawer.getByRole('button',{name:'配置预检',exact:true}).click();await capture(page,'F02-deleted-invalid-item');await expect(drawer.getByText('配置预检通过',{exact:true})).toBeVisible();
});

test('F02 fields with same key in different sections keep isolated errors',async({page})=>{
  test.skip(phase!=='state');const drawer=await openModbus(page);await drawer.getByLabel(/^连接超时/).fill('invalid');await drawer.getByRole('tab',{name:'采样',exact:true}).click();await drawer.getByLabel(/^采样超时/).fill('1000');let requests=0;page.on('request',request=>{if(request.url().endsWith('/device-configurations/validate'))requests++;});await drawer.getByRole('button',{name:'配置预检',exact:true}).click();await page.waitForTimeout(500);await writeFile(path.join(evidence,'F02-section-error-identity.json'),JSON.stringify({server_precheck_requests:requests},null,2));await capture(page,'F02-section-error-isolation');expect(requests).toBe(0);await expect(drawer.getByText('参数操作未完成',{exact:true})).toBeVisible();
});


test('a real changed-scope paging error clears the old window and automatically gets a first snapshot',async({page})=>{
  test.skip(phase!=='state');await instrument(page);const credentials=JSON.parse(await readFile(path.join(root,'cloud-precision','private-credentials.json'),'utf8'));await page.goto(precisionCloud+'/index.html');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill(credentials.password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('button',{name:'退出',exact:true})).toBeVisible();const previous=JSON.parse(await readFile(path.join(evidence,'F01-http-sse-snapshot-race.json'),'utf8'));await route(page,'data?device=agv-1');await page.getByLabel('测点名称').fill(previous.key);await page.getByLabel('历史时间范围').click();await page.locator('.ant-select-dropdown:visible').getByText('最近24小时',{exact:true}).click();await page.getByRole('button',{name:'查询历史',exact:true}).click();const table=page.locator('.ant-card').filter({has:page.getByText('精确观测记录',{exact:true})}).locator('tbody .ant-table-row');await expect(table).toHaveCount(100);await expect(page.getByRole('button',{name:'下一页',exact:true})).toBeEnabled();let rejected=false;let error:any;await page.route('**/api/sf/v1/queries/trend',async intercept=>{const value=JSON.parse(intercept.request().postData()||'{}');if(value.page_token&&!rejected){rejected=true;await intercept.continue({postData:JSON.stringify({...value,from_ms:value.from_ms+1})});}else await intercept.continue();});page.on('response',async response=>{if(response.url().endsWith('/queries/trend')&&response.status()===409)error=await response.json();});await page.getByRole('button',{name:'下一页',exact:true}).click();await expect.poll(()=>error?.code).toBe('query_changed');await expect(table).toHaveCount(100);await expect(page.getByRole('button',{name:'上一页',exact:true})).toBeDisabled();await expect(page.getByLabel('测点名称')).toHaveValue(previous.key);await writeFile(path.join(evidence,'query-paging-scope-reset.json'),JSON.stringify({scope_key:previous.key,error,first_page_rows:await table.count()},null,2));await capture(page,'query-paging-error-new-snapshot');
});
