import { test, expect } from './phase5-support';
import { api, capture, choose, get, login, route, snapshot } from './phase5-support';
test('read-only release identity can inspect authorized releases without configuration management requests', async ({ page }) => {
  test.skip(!['permissions-before', 'permissions'].includes(process.env.SF_PHASE5_CASES || ''));
  await login(page, 'release', 'index.html', true); await route(page, 'releases?deployment=deploy-validation-a01-b');
  await expect(page.getByRole('button', { name: '组合固定发布', exact: true })).toBeDisabled();
  await expect(page.getByTestId('release-detail')).toContainText('deploy-validation-a01-b');
  await expect(page.getByRole('button', { name: '退回旧发布', exact: true })).toBeDisabled();
  await capture(page, 'readonly-release-view');
  await route(page, 'workload-identities');
  await expect(page.getByRole('button', { name: '登记工作负载身份', exact: true })).toBeDisabled();
  await expect(page.getByRole('row').filter({ hasText: 'release-b' }).first()).toContainText('release-runtime');
  await expect(page.getByRole('row').filter({ hasText: 'release-b' }).first().getByRole('button', { name: '轮换私有凭据', exact: true })).toBeDisabled();
  await capture(page, 'readonly-workload-view');
});
test('release editor can compose authorized fixed content without the configuration administration directory', async ({ page }) => {
  test.skip(process.env.SF_PHASE5_CASES !== 'permissions-editor');
  await login(page); await route(page, 'releases?deployment=deploy-validation-a01-b');
  await expect(page.getByTestId('release-detail')).toContainText('deploy-validation-a01-b');
  await expect(page.getByRole('button', { name: '组合固定发布', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '组合固定发布', exact: true }).click();
  await choose(page, '参考已有固定清单', 'release-validation-a01-b');
  const id = 'frontend-editor-fixed-' + Date.now();
  await page.getByLabel('固定发布身份', { exact: true }).fill(id);
  await page.getByLabel('固定发布名称', { exact: true }).fill('工程师登记固定程序、规则与配置');
  await page.getByRole('button', { name: '校验依赖与兼容', exact: true }).click();
  await expect(page.getByText('依赖与兼容校验通过', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '登记固定发布', exact: true }).click();
  await expect(page.getByRole('dialog', { name: '组合程序、规则和配置' })).toBeHidden();
  const saved = await get(page, '/releases/' + id); await snapshot('editor-fixed-record', saved);
  await expect(page.getByTestId('release-detail')).toContainText('deploy-validation-a01-b'); await capture(page, 'editor-authorized-release-view');
  await route(page, 'workload-identities');
  await expect(page.getByRole('button', { name: '登记工作负载身份', exact: true })).toBeDisabled();
  await expect(page.getByRole('row').filter({ hasText: 'release-b' }).first()).toContainText('release-runtime'); await capture(page, 'editor-workload-readonly');
  const forbidden = await api(page, '/config'); expect(forbidden.status).toBe(403);
  const allowed = await get(page, '/releases/' + id); expect(allowed.id).toBe(id);
  await snapshot('editor-formal-authority-check', { directory: forbidden, authorized_release: allowed });
  await expect(page.getByRole('row').filter({ hasText: 'release-b' }).first()).toContainText('release-runtime');
});
