import { test, expect, api, capture, directory, get, login, releaseCloud, snapshot, choose } from './phase5-support';
import { createBatch, waitDeployment } from './phase5-release-helpers';
import { readFile } from 'node:fs/promises';
import { parseExactJSON } from '../src/precision';
import { restartReleaseAgent } from './phase5-fixture-controls';
test('actual application failure stops later batch and incompatible rollback gives recovery before compatible rollback runs', async ({ page }) => {
  test.skip(process.env.SF_PHASE5_CASES !== 'legacy-failure-rollback'); test.setTimeout(150000);
  await login(page);
  const source = JSON.parse(await readFile(directory + '/browser-templates-second/five-template-evolved.state.json', 'utf8'));
  const prior = (await get<any[]>(page, '/release-deployments')).filter(value => !['completed', 'cancelled'].includes(value.state) && value.targets?.some((target: any) => ['release-a', 'release-b'].includes(target.identity_id)));
  for (const value of prior) {
    expect(value.state).toBe('failed');
    await page.goto(releaseCloud + '/index.html#releases?deployment=' + value.id);
    await page.getByLabel('发布处理原因', { exact: true }).fill('保留此前模板夹具协议不足的结果，开始独立失败与退回验证');
    const request = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/actions'));
    await page.getByRole('button', { name: '取消后续发布', exact: true }).click(); expect((await request).status()).toBe(200);
  }
  const cacheRestored = await restartReleaseAgent('a');
  await expect.poll(async () => { try { await fetch('http://127.0.0.1:60050/', { signal: AbortSignal.timeout(1000) }); return true; } catch { return false; } }, { timeout: 12000 }).toBe(true);
  await snapshot('prior-verified-program-cache-restored', cacheRestored);
  const nonce = Date.now(), id = 'frontend-failed-' + nonce;
  const base = await get(page, '/releases/release-validation-a01-b');
  const bConfiguration = base.manifest.components.find((component: any) => component.configuration?.id === 'edge-b/mqtt-b');
  const bRules = base.manifest.components.filter((component: any) => component.kind === 'rule' && (!component.target_node_ids?.length || component.target_node_ids.includes('edge-b')));
  const baseConfigurations = base.manifest.components.filter((component: any) => component.kind === 'configuration');
  const manifest = { ...source.release.manifest, id: 'frontend-failure-source-' + nonce, name: '实际应用失败验证的双节点固定清单', template: undefined, components: [...source.release.manifest.components, ...baseConfigurations, ...bRules] };
  const checked = await api(page, '/releases/validate', manifest); await snapshot('failure-source-validation', { manifest, response: checked }); expect(checked.status).toBe(200); expect((parseExactJSON(checked.text) as any).valid).toBe(true);
  const registered = await api(page, '/releases', { request_id: manifest.id, manifest }); expect(registered.status).toBe(200);
  await snapshot('failure-fixed-source', { source: source.release, additional: bConfiguration, validation: parseExactJSON(checked.text), registered: parseExactJSON(registered.text) });
  await page.reload();
  await createBatch(page, id, manifest.id, [['release-a'], ['release-b']], '实际配置消费者缺少协议时核对程序失败与后续批次停止');
  const failed = await waitDeployment(page, id, value => value.state === 'failed' && value.targets[0].state === 'failed', 30000);
  expect(failed.targets[0].prepared_sha256).toBe(failed.release_sha256); expect(failed.targets[0].failure_component).toBe('program');
  expect(failed.targets[1].state).toBe('pending'); expect(failed.batches[1].entered_ms).toBe(0); expect(failed.batches[1].completed_ms).toBe(0);
  await snapshot('application-failed-later-batch-stopped', failed); await capture(page, 'application-failed-later-batch-stopped');
  await page.getByRole('button', { name: '核对状态并更新操作依据', exact: true }).click();
  await page.getByLabel('发布处理原因', { exact: true }).fill('数据库迁移11先核对旧版本兼容条件，再选择受支持的固定发布');
  await choose(page, '退回的固定发布', 'release-legacy');
  await page.getByLabel('退回批次身份', { exact: true }).fill('frontend-incompatible-' + nonce);
  let response = page.waitForResponse(value => value.request().method() === 'POST' && value.url().endsWith('/rollback'));
  await page.getByRole('button', { name: '退回旧发布', exact: true }).click(); let received = await response; expect(received.status()).toBe(400);
  const incompatibility = parseExactJSON(await received.text()) as any;
  await expect(page.getByText('发布处理未完成', { exact: true })).toBeVisible();
  await expect(page.getByLabel('发布处理原因', { exact: true })).toHaveValue('数据库迁移11先核对旧版本兼容条件，再选择受支持的固定发布');
  expect(JSON.stringify(incompatibility)).toContain('migration'); await snapshot('incompatible-rollback-recovery', incompatibility); await capture(page, 'incompatible-rollback-recovery');
  await choose(page, '退回的固定发布', 'release-v1');
  const rollbackID = 'frontend-compatible-rollback-' + nonce; await page.getByLabel('退回批次身份', { exact: true }).fill(rollbackID);
  response = page.waitForResponse(value => value.request().method() === 'POST' && value.url().endsWith('/rollback'));
  await page.getByRole('button', { name: '退回旧发布', exact: true }).click(); received = await response; expect(received.status()).toBe(200);
  const rollbackCache = await restartReleaseAgent('a'); await snapshot('rollback-source-owner-restored', rollbackCache);
  const completed = await waitDeployment(page, rollbackID, value => value.state === 'completed' && value.targets.every((target: any) => target.report_fresh && target.state === 'running'), 50000);
  expect(completed.rollback_of).toBe(id);
  const old = await get(page, '/releases/release-v1'); const program = old.manifest.components.find((component: any) => component.kind === 'program');
  for (const target of completed.targets) { expect(target.running_sha256).toBe(old.sha256); expect(target.runtime.program_sha256).toBe(program.sha256); expect(target.runtime.migration_version).toBe(11); }
  await snapshot('compatible-rollback-actual-running', { before: failed, after: completed, source: old }); await capture(page, 'compatible-rollback-actual-running');
  await createBatch(page, 'frontend-rollback-recovery-' + nonce, 'release-validation-a01-b', [['release-a'], ['release-b']], '退回验证完成，恢复最终组合程序及固定配置');
  const restored = await waitDeployment(page, 'frontend-rollback-recovery-' + nonce, value => value.state === 'completed' && value.targets.every((target: any) => target.report_fresh), 50000);
  await snapshot('rollback-restored-final-program', restored); await capture(page, 'rollback-restored-final-program');
});
