import { test, expect, type Page } from '@playwright/test';
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { root, evidence, phase, aiURL, clean, login, capture, route, jsonAPI } from './phase4-support';

test.afterEach(async({page},info)=>{if(info.status!==info.expectedStatus)await capture(page,'failure-'+info.title.slice(0,50).replace(/[^a-z0-9]+/gi,'-'));});

test.beforeEach(async({request})=>{if(phase!=='ai')return;const credentials=JSON.parse(await readFile(path.join(root,process.env.SF_PHASE4_AI_DIR||'ai-first','private-credentials.json'),'utf8'));const response=await request.post(aiURL+'/api/sf/v1/login',{data:{login:'operator-a',password:credentials.password}});const auth=await response.json();expect((await request.post(aiURL+'/__fixture/state',{headers:{Authorization:'Bearer '+auth.token},data:{action:'restore'}})).status()).toBe(200);});

async function detail(page:Page,id:string) { const response=await jsonAPI(page,'/investigations/'+encodeURIComponent(id)); expect(response.status).toBe(200); return JSON.parse(response.text); }
async function investigate(page:Page,text:string) {
  const paragraph=page.locator('.chat-history').getByText(/调查身份 /); const before=await paragraph.count()? (await paragraph.innerText()).match(/调查身份 ([^，]+)/)?.[1] : '';
  await page.getByLabel('发送给 AI 助手的消息').fill(text); await page.getByRole('button',{name:'发送',exact:true}).click();
  let id=''; await expect.poll(async()=>{ if(!await paragraph.count())return false;id=(await paragraph.innerText()).match(/调查身份 ([^，]+)/)?.[1]||'';return !!id&&id!==before;}).toBe(true);
  await expect.poll(async()=> (await detail(page,id)).status,{timeout:20000}).not.toBe('running');
  const result=await detail(page,id); await expect(page.getByText(new RegExp('调查身份 '+id))).toBeVisible();
  await expect(page.getByRole('button',{name:'发送',exact:true})).not.toHaveClass(/ant-btn-loading/); return result;
}
async function fixture(page:Page,body:unknown) { return page.evaluate(async body=>{const response=await fetch('/__fixture/state',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+sessionStorage.getItem('smartfactory.session.'+location.host)},body:JSON.stringify(body)});return {status:response.status,text:await response.text()};},body); }

test('AI five actual tools show byte-identical evidence and navigate escaped resource identities',async({page})=>{
  test.skip(phase!=='ai'); await login(page,'ai'); await route(page,'assistant'); const result=await investigate(page,'调查温度、执行与历史依据');
  expect(result.evidence_status).toBe('supported');expect(result.evidence).toHaveLength(5);
  const transcript=(await readFile(path.join(root,process.env.SF_PHASE4_AI_DIR||'ai-first','model-visible-results.jsonl'),'utf8')).trim().split('\n').filter(Boolean).map(line=>JSON.parse(line));
  const checked=[];
  for(const item of result.evidence){const response=await jsonAPI(page,`/investigations/${encodeURIComponent(result.id)}/evidence/${encodeURIComponent(item.id)}`);expect(response.status).toBe(200);const value=JSON.parse(response.text);const sha=createHash('sha256').update(value.visible_content).digest('hex');expect(sha).toBe(value.visible_sha256);const actual=transcript.find(row=>(row.tool_call_id||row.ToolCallID)===value.tool_call_id&&Object.values(row).some(content=>content===value.visible_content));expect(actual).toBeTruthy();expect(Object.values(actual).some(content=>content===value.visible_content)).toBe(true);checked.push(value);}
  await page.getByRole('button',{name:'查看工具依据',exact:true}).first().click();const drawer=page.getByRole('dialog',{name:'模型实际取得的依据'});await expect(drawer.getByTestId('model-visible-content')).toHaveText(checked[0].visible_content,{useInnerText:true});await capture(page,'ai-five-tools-visible-evidence');await drawer.getByRole('button',{name:'关闭',exact:true}).click();
  const special=await investigate(page,'读取身份 调查/温度:一号');expect(special.evidence_status).toBe('supported');await page.getByRole('button',{name:'查看依据原文',exact:true}).first().click();const source=page.getByRole('dialog',{name:'模型实际取得的依据'});const link=source.getByRole('link',{name:/definition \/ 调查\/温度:一号/});await expect(link).toHaveAttribute('href',/#analysis\?definition=%E8%B0%83%E6%9F%A5%2F%E6%B8%A9%E5%BA%A6%3A%E4%B8%80%E5%8F%B7/);await link.click();await expect(page.getByLabel('定义名称')).toBeVisible();await capture(page,'ai-escaped-definition-navigation');await writeFile(path.join(evidence,'ai-byte-correspondence.json'),JSON.stringify(clean({result,checked,special,transcript_checks:checked.length}),null,2));
});

test('AI forged cross-investigation failed empty and budget references retain current statuses',async({page})=>{
  test.skip(phase!=='ai');await login(page,'ai');await route(page,'assistant');await investigate(page,'调查温度、执行与历史依据');
  const cases:[string,string][]=[['跨调查引用','cross_investigation'],['伪造引用','unknown'],['空查询','empty'],['查询失败','tool_error'],['超预算','budget_exceeded'],['无依据回答','missing']];const results=[];
  for(const [input,status]of cases){const result=await investigate(page,input);if(status==='missing')expect(result.evidence_status).toBe(status);else expect(result.references.some((reference:any)=>reference.status===status)).toBe(true);expect(result.evidence_status).not.toBe('supported');results.push({input,status,result});await capture(page,'ai-'+status);}
  await writeFile(path.join(evidence,'ai-reference-states.json'),JSON.stringify(clean(results),null,2));
});

test('AI revoked permission clears visible answer and evidence then restores and expires current data',async({page})=>{
  test.skip(phase!=='ai');await login(page,'ai');await route(page,'assistant');const result=await investigate(page,'调查温度、执行与历史依据');const evidenceID=result.evidence[0].id;await page.getByRole('button',{name:'查看依据原文',exact:true}).first().click();await expect(page.getByTestId('model-visible-content')).toBeVisible();expect((await fixture(page,{action:'revoke'})).status).toBe(200);await page.getByRole('button',{name:'更新当前依据状态',exact:true}).click();await expect(page.getByTestId('model-visible-content')).toBeHidden();await expect(page.locator('body')).not.toContainText(result.answer);const revoked=await detail(page,result.id);expect(revoked.answer||'').toBe('');expect(revoked.evidence.some((item:any)=>item.access_status==='forbidden')).toBe(true);await capture(page,'ai-revoked-cache-cleared');
  expect((await fixture(page,{action:'restore'})).status).toBe(200);await page.reload();await route(page,'assistant?investigation='+encodeURIComponent(result.id));await expect(page.locator('.message-assistant')).toContainText(result.answer);await capture(page,'ai-restored-permission');
  expect((await fixture(page,{action:'expire',investigation_id:result.id})).status).toBe(200);await page.getByRole('button',{name:'更新依据状态',exact:true}).click();await expect(page.locator('body')).not.toContainText(result.answer);const expired=await detail(page,result.id);expect(expired.answer||'').toBe('');const response=await jsonAPI(page,`/investigations/${result.id}/evidence/${evidenceID}`);expect(response.status).toBe(410);await capture(page,'ai-expired-answer-cleared');await writeFile(path.join(evidence,'ai-permission-expiry.json'),JSON.stringify(clean({investigation_id:result.id,revoked,expired,evidence_status:response.status}),null,2));
});

test('AI user switch and expired session clear previous investigation and unsaved editor',async({page})=>{
  test.skip(phase!=='ai');await login(page,'ai');await route(page,'assistant');const result=await investigate(page,'读取身份 调查/温度:一号');await route(page,'analysis?definition='+encodeURIComponent('调查/温度:一号'));await expect(page.getByLabel('定义名称')).toBeVisible();await page.getByLabel('定义名称').fill('前一账号尚未提交的编辑');await route(page,'runtime');await page.getByRole('button',{name:'退出',exact:true}).click();await expect(page.getByLabel('账号',{exact:true})).toBeVisible();await login(page,'ai','index.html','operator-b');await route(page,'assistant');await expect(page.getByText(result.id,{exact:true})).toBeHidden();expect((await jsonAPI(page,'/investigations/'+result.id)).status).toBe(404);await route(page,'analysis');await expect(page.getByLabel('定义名称')).toBeHidden();await capture(page,'ai-user-isolation-and-editor-cleared');await jsonAPI(page,'/logout',{});await route(page,'assistant');await expect(page.getByLabel('账号',{exact:true})).toBeVisible();expect(await page.evaluate(()=>Object.keys(sessionStorage).filter(key=>key.startsWith('smartfactory.session.')))).toEqual([]);await capture(page,'ai-expired-session-login');
});

test('AI interrupted and service-error streams show saved terminal investigation state',async({page})=>{
  test.skip(phase!=='ai');await login(page,'ai');await route(page,'assistant');const results=[];
  for(const input of ['模拟中断','模拟服务错误','模拟超时']){const result=await investigate(page,input);expect(['interrupted','failed']).toContain(result.status);expect(result.error).toBeTruthy();expect(result.evidence_status).toBe('unsupported');results.push({input,result});await capture(page,'ai-terminal-'+results.length);}
  await writeFile(path.join(evidence,'ai-terminal-states.json'),JSON.stringify(clean(results),null,2));
});

test('AI expiry polling hides an open cached evidence before it is requested again',async({page})=>{
  test.skip(phase!=='ai');await login(page,'ai');await route(page,'assistant');const result=await investigate(page,'调查温度、执行与历史依据');const id=result.evidence[0].id;await page.getByRole('button',{name:'查看依据原文',exact:true}).first().click();await expect(page.getByTestId('model-visible-content')).toBeVisible();expect((await fixture(page,{action:'expire',investigation_id:result.id})).status).toBe(200);await expect(page.getByTestId('model-visible-content')).toBeHidden();await expect(page.locator('body')).not.toContainText(result.answer);const expired=await detail(page,result.id);expect(expired.evidence.every((item:any)=>item.arguments===null&&!item.visible_content&&!item.resources?.length)).toBe(true);expect((await jsonAPI(page,`/investigations/${result.id}/evidence/${id}`)).status).toBe(410);await page.getByRole('button',{name:'更新当前依据状态',exact:true}).click();await expect(page.getByText('当前依据无法读取',{exact:true})).toBeVisible();await capture(page,'ai-open-evidence-expired-cleared');await writeFile(path.join(evidence,'ai-open-evidence-expired.json'),JSON.stringify(clean({expired,original_answer:result.answer,detail_http_status:410}),null,2));
});

test('AI original asset deletion after definition rebind clears the original cited content',async({page})=>{
  test.skip(phase!=='ai');await login(page,'ai');await route(page,'assistant');expect((await fixture(page,{action:'prepare_original_resource'})).status).toBe(200);const result=await investigate(page,'读取身份 调查/温度:一号');expect(result.evidence_status).toBe('supported');const id=result.evidence[0].id;const original=await jsonAPI(page,`/investigations/${result.id}/evidence/${id}`);expect(original.status).toBe(200);const value=JSON.parse(original.text);expect(value.resources.some((resource:any)=>resource.kind==='resource'&&resource.id==='private-factory')).toBe(true);await page.getByRole('button',{name:'查看依据原文',exact:true}).first().click();await expect(page.getByTestId('model-visible-content')).toHaveText(value.visible_content,{useInnerText:true});expect((await fixture(page,{action:'rebind_definition'})).status).toBe(200);const rebound=await jsonAPI(page,`/investigations/${result.id}/evidence/${id}`);expect(rebound.status).toBe(200);expect(JSON.parse(rebound.text).visible_content).toBe(value.visible_content);await capture(page,'ai-original-resource-after-rebind');expect((await fixture(page,{action:'delete_original_resource'})).status).toBe(200);await page.getByRole('button',{name:'更新当前依据状态',exact:true}).click();await expect(page.getByTestId('model-visible-content')).toBeHidden();await expect(page.locator('body')).not.toContainText(result.answer);expect((await jsonAPI(page,`/investigations/${result.id}/evidence/${id}`)).status).toBe(404);const deleted=await detail(page,result.id);expect(deleted.answer||'').toBe('');expect(deleted.messages||[]).toEqual([]);expect(deleted.evidence_status).toBe('unsupported');expect(deleted.references.every((item:any)=>item.status==='deleted')).toBe(true);expect(deleted.evidence.every((item:any)=>item.access_status==='deleted'&&item.arguments===null&&!item.visible_content&&!item.resources?.length)).toBe(true);await writeFile(path.join(evidence,'ai-original-resource-deleted.json'),JSON.stringify(clean({original:value,rebound:JSON.parse(rebound.text),deleted}),null,2));await capture(page,'ai-original-resource-deleted-cleared');
});

test('AI deleted source and explicit investigation deletion remove stored visible content',async({page})=>{
  test.skip(phase!=='ai');await login(page,'ai');await route(page,'assistant');const result=await investigate(page,'读取身份 调查/温度:一号');const evidenceID=result.evidence[0].id;expect((await fixture(page,{action:'delete_resource'})).status).toBe(200);await page.getByRole('button',{name:'更新依据状态',exact:true}).click();await expect(page.locator('body')).not.toContainText(result.answer);expect((await jsonAPI(page,`/investigations/${result.id}/evidence/${evidenceID}`)).status).toBe(404);const deletedSource=await detail(page,result.id);expect(deletedSource.answer||'').toBe('');await capture(page,'ai-deleted-resource');await page.getByRole('button',{name:'删除此调查内容',exact:true}).click();await expect(page.locator('.message-assistant')).toBeHidden();const deleted=await detail(page,result.id);expect(deleted.status).toBe('deleted');expect(deleted.messages||[]).toEqual([]);expect(deleted.evidence.every((item:any)=>!item.visible_content&&!item.arguments&&!item.resources?.length)).toBe(true);await writeFile(path.join(evidence,'ai-deleted-content.json'),JSON.stringify(clean({deletedSource,deleted}),null,2));await capture(page,'ai-investigation-content-deleted');
});
