import { useEffect, useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Alert, Button, Card, Descriptions, Drawer, Form, Input, Modal, Select, Space, Table, Tag } from 'antd';
import { json, useResource } from './api';
import { callOperation, type Contract } from './generated-client';
import { useWindowQuery } from './query';
import { exactTimestamp } from './precision';
import { PageTitle, ErrorNotice } from './views';

const labels: Record<string, string> = { acknowledge: '确认告警', assign: '分配责任人', note: '添加备注', complete: '完成处置', reopen: '再次处理' };
export function AlarmWorkbench({ refreshMS, initialID = '' }: { refreshMS: number; initialID?: string }) {
  const [search, setSearch] = useState(''); const [active, setActive] = useState<boolean>(); const [handling, setHandling] = useState<string>(); const [pageToken, setPageToken] = useState(''); const [history, setHistory] = useState<string[]>([]);
  const result = useWindowQuery('alarms', { search, active, handling_status: handling, limit: 20, page_token: pageToken || undefined }, pageToken ? 0 : refreshMS);
  useEffect(()=>{if(result.resetRequired && pageToken){setPageToken('');setHistory([]);}},[result.resetRequired,pageToken]);
  const [selected, setSelected] = useState(initialID); const detail = useResource<Contract<'AlarmDetail'>>(selected ? '/alarms/' + encodeURIComponent(selected) : null, refreshMS);
  const [review, setReview] = useState<{ detail: Contract<'AlarmDetail'>; action: string; request: string }>(); const [reason, setReason] = useState(''); const [assignee, setAssignee] = useState('');
  useEffect(() => { if (initialID) setSelected(initialID); }, [initialID]);
  const mutation = useMutation({ mutationFn: async () => {
    if (!review || !reason.trim()) throw new Error('请填写处置理由');
    const saved = await callOperation('post_alarms_id_actions', { parameters: { path: { id: review.detail.alarm?.id ?? '' } }, body: { request_id: review.request, expected_version: review.detail.case?.version ?? 0, expected_action_version: review.detail.action_version ?? '', action: review.action as Contract<'AlarmActionInput'>['action'], reason, ...(review.action === 'assign' ? { assignee_id: assignee } : {}) } }, { exact: true });
    setReview(undefined); setReason(''); await detail.reload(); await result.reload(); return saved;
  }, onError: () => { void detail.reload(); } });
  const filter = (change: () => void) => { change(); setPageToken(''); setHistory([]); };
  return <><PageTitle title="告警处置" note="核对规则状态、原生状态和人工处置，按照当前允许操作保存确认、责任人与理由。" actions={<Button onClick={() => { void result.reload(); void detail.reload(); }}>更新告警</Button>} /><ErrorNotice error={result.error || detail.error} retry={() => { void result.reload(); void detail.reload(); }} />
    <Card><Space className="query-toolbar" wrap><Input aria-label="告警搜索" placeholder="规则、设备或告警身份" value={search} onChange={event => filter(() => setSearch(event.target.value))} /><Select aria-label="规则触发状态" allowClear placeholder="全部触发状态" style={{ width: 180 }} value={active} onChange={value => filter(() => setActive(value))} options={[{ value: true, label: '规则仍在触发' }, { value: false, label: '规则已恢复' }]} /><Select aria-label="人工处置状态" allowClear placeholder="全部处置状态" style={{ width: 180 }} value={handling} onChange={value => filter(() => setHandling(value))} options={['open','in_progress','completed'].map(value => ({ value, label: value }))} /><Tag>{result.streamStatus}</Tag></Space>
      <Table rowKey="id" loading={result.loading} pagination={false} scroll={{ x: 950 }} dataSource={result.data?.items ?? []} columns={[{ title: '告警与设备', render: (_, row) => { const data = row.data as Record<string, unknown>; return <><strong>{String(data.definition_id)}</strong><small className="table-subtext">{String(data.entity_id)}</small></>; } }, { title: '级别', render: (_, row) => String((row.data as Record<string, unknown>).severity) }, { title: '规则状态', render: (_, row) => <Tag color={(row.data as Record<string, unknown>).active ? 'orange' : 'green'}>{(row.data as Record<string, unknown>).active ? '仍在触发' : '已恢复'}</Tag> }, { title: '人员确认', render: (_, row) => (row.data as Record<string, unknown>).acknowledged ? '已确认' : '等待确认' }, { title: '责任人', render: (_, row) => String((row.data as Record<string, unknown>).assignee_id || '尚未分配') }, { title: '业务版本 / 提交修订', render: (_, row) => `${String(row.version)} / ${row.revision}` }, { title: '操作', render: (_, row) => <Button onClick={() => setSelected(row.id ?? '')}>查看告警详情</Button> }]} />
      <Space className="section-actions"><Button disabled={!history.length} onClick={() => { setPageToken(history.at(-1) ?? ''); setHistory(history.slice(0,-1)); }}>上一页</Button><Button disabled={!result.data?.has_more || !result.data.next_page_token} onClick={() => { setHistory([...history, pageToken]); setPageToken(result.data!.next_page_token!); }}>下一页</Button><span>本页 {result.data?.items?.length ?? 0} 条{result.data?.has_more ? '，仍有后续结果' : ''}</span></Space>
    </Card>
    <Drawer title="告警生命周期与处置" open={!!selected} onClose={() => setSelected('')} width="min(1000px,100vw)">
      {detail.data && <><Descriptions column={2} items={[{ key: 'id', label: '告警身份', children: detail.data.alarm?.id }, { key: 'version', label: '观测版本', children: String(detail.data.alarm?.version) }, { key: 'active', label: '规则判断', children: detail.data.alarm?.active ? '当前仍在触发' : '当前已经恢复' }, { key: 'level', label: '级别', children: detail.data.alarm?.severity }, { key: 'value', label: '当前精确值', children: json(detail.data.alarm?.value) }, { key: 'count', label: '合并次数', children: String(detail.data.alarm?.count) }, { key: 'ack', label: '人工确认', children: detail.data.case?.acknowledged ? '已经确认' : '等待确认' }, { key: 'owner', label: '责任人', children: detail.data.case?.assignee_id || '尚未分配' }, { key: 'case', label: '处置状态 / 人工版本', children: `${detail.data.case?.status} / ${String(detail.data.case?.version)}` }, { key: 'native', label: '原生状态', children: detail.data.native ? `${detail.data.native.acknowledged ? '已确认' : '未确认'} / ${detail.data.native.cleared ? '已清除' : '未清除'}` : '没有原生映射' }, { key: 'sync', label: '原生同步', children: `${detail.data.native_sync?.status} / 最近成功 ${exactTimestamp(detail.data.native_sync?.success_ms)}` }, { key: 'syncfail', label: '失败映射', children: String(detail.data.native_sync?.failed_mappings ?? 0) }]} />
      {!!detail.data.case?.conflict_fields?.length && <Alert type="warning" title="责任信息存在同步冲突" description={detail.data.case.conflict_fields.join('、')} />}{!!detail.data.case?.pending_basis?.length && <Alert type="warning" title="处置正在等待前序同步依据" />}
      <Space wrap className="section-actions">{detail.data.allowed_actions?.map(action => <Button key={action.action} disabled={!action.allowed} title={action.reason} onClick={() => { setReview({ detail: structuredClone(detail.data!), action: action.action ?? '', request: crypto.randomUUID() }); setReason(''); setAssignee(''); mutation.reset(); }}>{labels[action.action ?? ''] || action.action}</Button>)}</Space>
      <Table rowKey="id" size="small" dataSource={detail.data.case?.operations ?? []} scroll={{ x: 780 }} columns={[{ title: '动作', dataIndex: 'action', render: value => labels[value] || value }, { title: '理由', dataIndex: 'reason' }, { title: '人员', render: (_, operation) => operation.actor?.user_id }, { title: '时间', dataIndex: 'at_ms', render: exactTimestamp }, { title: '来源 / 序号', render: (_, operation) => `${operation.source_id} / ${String(operation.source_sequence)}` }]} /></>}
    </Drawer>
    <Modal title={labels[review?.action ?? ''] || '告警处置确认'} open={!!review} onCancel={() => setReview(undefined)} onOk={() => mutation.mutate()} confirmLoading={mutation.isPending} okText="提交处置">
      <p>本次操作依据人工版本 {String(review?.detail.case?.version)} 与打开确认流程时的动作版本；持续观测中的计数和最新值继续更新。</p><p className="reviewed-version">已阅动作版本 <code>{review?.detail.action_version}</code></p>
      {mutation.error && <Alert type="error" title="处置提交未完成" description={mutation.error.message} />}{mutation.error && <Button onClick={() => { if (review && detail.data) { setReview({ ...review, detail: structuredClone(detail.data), request: crypto.randomUUID() }); mutation.reset(); } }}>采用更新后的告警依据</Button>}
      <Form layout="vertical">{review?.action === 'assign' && <Form.Item label="责任人身份" required><Input aria-label="责任人身份" value={assignee} onChange={event => setAssignee(event.target.value)} /></Form.Item>}<Form.Item label="处置理由" required><Input.TextArea aria-label="处置理由" value={reason} rows={4} maxLength={4000} onChange={event => setReason(event.target.value)} /></Form.Item></Form>
    </Modal></>;
}
