import { useEffect, useState } from 'react';
import { Alert, Button, Card, Input, Select, Space, Table, Tag } from 'antd';
import { json, useResource } from './api';
import { queryAllPages, queryData, useWindowQuery } from './query';
import { Trend } from './chart';
import { exactTimestamp, stringifyExactJSON } from './precision';
import { PageTitle, ErrorNotice, Quality, RevisionModal, StateTag } from './views';
import type { Entity, Point, Revision } from './types';

export function DataPage({ refreshMS, initialDevice = '' }: { refreshMS: number; initialDevice?: string }) {
  const entities = useResource<Entity[]>('/entities'); const [device,setDevice] = useState(initialDevice); const [key,setKey] = useState(''); const [hours,setHours] = useState(1); const [resolution,setResolution] = useState('raw');
  const [range,setRange] = useState({from:Date.now()-3600000,to:Date.now()}); const [token,setToken] = useState(''); const [pages,setPages] = useState<string[]>([]); const [revision,setRevision] = useState<Revision|null>(null); const [exporting,setExporting] = useState(false); const [exportError,setExportError] = useState('');
  const scope = { resource_ids: device ? [device] : [], keys:key ? key.split(',').map(value => value.trim()).filter(Boolean) : [], from_ms:range.from,to_ms:range.to,resolution,limit:100,page_token:token||undefined };
  const result = useWindowQuery('trend',scope,token ? 0 : refreshMS); const data = queryData(result.data);
  useEffect(()=>{ if(result.resetRequired && token){setToken('');setPages([]);} },[result.resetRequired,token]);
  useEffect(() => { setDevice(initialDevice); setToken(''); setPages([]); }, [initialDevice]);
  const search = () => { setRange({from:Date.now()-hours*3600000,to:Date.now()}); setToken(''); setPages([]); };
  const exportData = async () => { setExporting(true); setExportError(''); try { const page = await queryAllPages('trend',{...scope,page_token:undefined,limit:2000}); const blob = new Blob([stringifyExactJSON(page,2)],{type:'application/json'}); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href=url; link.download='smartfactory-trend-exact.json'; link.click(); URL.revokeObjectURL(url); } catch(error) {setExportError(error instanceof Error ? error.message : String(error));} finally {setExporting(false);} };
  return <><PageTitle title="数据监控" note="按固定时间范围、设备和测点查询提交快照，工具提示、数据表和完整导出保存精确原值。" actions={<Button loading={exporting} onClick={() => void exportData()}>导出完整精确数据</Button>} /><ErrorNotice error={result.error||exportError} retry={() => void result.reload()} />
    <Card><Space className="query-toolbar" wrap><Select aria-label="查询设备" allowClear placeholder="所有可访问设备" style={{minWidth:230}} value={device||undefined} onChange={value=>{setDevice(value??'');setToken('');setPages([]);}} options={(entities.data??[]).map(entity=>({value:entity.id,label:entity.name}))} /><Input aria-label="测点名称" placeholder="测点名称，可留空" value={key} onChange={event=>{setKey(event.target.value);setToken('');setPages([]);}} /><Select aria-label="历史时间范围" value={hours} onChange={setHours} options={[{value:1,label:'最近1小时'},{value:24,label:'最近24小时'},{value:720,label:'最近30天'},{value:26280,label:'最近3年'}]} /><Select aria-label="数据粒度" value={resolution} onChange={value=>{setResolution(value);setToken('');setPages([]);}} options={['raw','minute','hour','day'].map(value=>({value,label:({raw:'原始精度',minute:'分钟汇总',hour:'小时汇总',day:'日汇总'} as Record<string,string>)[value]}))} /><Button type="primary" onClick={search}>查询历史</Button><Tag>{result.streamStatus}</Tag></Space><p>查询时间：{exactTimestamp(range.from)} 至 {exactTimestamp(range.to)}</p><Trend data={data} onRevision={setRevision} /><Quality data={data} />{result.data?.metadata?.quality_scope === 'page' && <p className="muted">有效、无效与不确定观测统计采用当前页；缺口与完整程度采用固定查询范围。</p>}</Card>
    <Card title="精确观测记录" className="section-card"><Table rowKey="id" size="small" loading={result.loading} dataSource={data?.points??[]} pagination={false} scroll={{x:1100}} columns={[{title:'设备时间',dataIndex:'observed_ms',render:exactTimestamp},{title:'设备',dataIndex:'device_id'},{title:'测点 / 单位',render:(_,point:Point)=>`${point.key} / ${point.unit||'无单位'}`},{title:'精确值',dataIndex:'value',render:value=><code>{typeof value==='string'?value:json(value)}</code>},{title:'质量',dataIndex:'quality',render:value=><StateTag status={value}/>},{title:'来源',dataIndex:'source_id'},{title:'修订',dataIndex:'revision',render:String}]} /><Space className="section-actions"><Button disabled={!pages.length} onClick={()=>{setToken(pages.at(-1)??'');setPages(pages.slice(0,-1));}}>上一页</Button><Button disabled={!result.data?.has_more||!result.data.next_page_token} onClick={()=>{setPages([...pages,token]);setToken(result.data!.next_page_token!);}}>下一页</Button><span>本页{data?.points.length??0}条{result.data?.has_more?'，仍有后续数据':''}</span></Space></Card>
    <Card title="来源与数据修订" className="section-card"><Table rowKey="id" size="small" dataSource={data?.sources??[]} columns={[{title:'来源',dataIndex:'id'},{title:'运行状态',dataIndex:'status'},{title:'最后通信',dataIndex:'last_seen_ms',render:exactTimestamp}]} /><Table rowKey="id" size="small" dataSource={data?.revisions??[]} columns={[{title:'时间',dataIndex:'at_ms',render:exactTimestamp},{title:'原因',dataIndex:'reason'},{title:'对比',render:(_,item:Revision)=><Button onClick={()=>setRevision(item)}>查看精确修订</Button>}]} /></Card><RevisionModal revision={revision} onClose={()=>setRevision(null)} /></>;
}
