import { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Card, Collapse, Descriptions, Drawer, Form, Input, Modal, Progress, Select, Space, Table, Tabs, Tag } from 'antd';
import { api, json, RequestError } from './api';
import { createAnalysisRun, getAnalysisRun, getAnalysisSnapshot, getAnalysisSteps, getShadowCandidate, getTask, listAnalysisRuns, listShadowCandidates, saveShadowCandidate, stopShadowCandidate, type Contract, type HistoryRun, type HistoryStep, type ShadowCandidate } from './generated-client';
import { useGeneratedResource } from './generated-resource';
import { buildHistoryRequest, buildShadowRequest, formalStatusText, historyComparisonText, historyStatusText, type HistoryFormInput } from './history-input';
import { exactTimestamp, stringifyExactJSON } from './precision';
import { taskPhaseText, taskStateText } from './task-status';
import type { Definition, User } from './types';
import { PageTitle } from './views';

const errorText = (error: unknown) => error instanceof Error ? error.message : String(error);
const kindNames: Record<string, string> = { replay: '历史回放', compare: '版本比较', shadow: '影子计算' };
function State({ value }: { value?: string }) { return <Tag color={value === 'completed' ? 'success' : value === 'failed' || value === 'budget_exceeded' ? 'error' : value === 'waiting_parent' ? 'warning' : 'default'}>{historyStatusText(value)}</Tag>; }
function download(name: string, value: unknown) {
  const url = URL.createObjectURL(new Blob([stringifyExactJSON(value, 2)], { type: 'application/json' }));
  const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url);
}
type Notice = { kind: 'success'; id: string; title: string } | { kind: 'warning' | 'error'; title: string; description: string };
const defaults: HistoryFormInput = { id: '', kind: 'replay', definitionID: '', from: String(Date.now() - 3600000), to: String(Date.now()), devices: '', keys: '', leftVersion: '1', rightVersion: '2', order: 'event_time', inputSource: 'retained', points: '[]', historySource: 'retained', history: '[]', parameters: '{}' };

export function HistoryAnalysis({ user, refreshMS, initialRun = '', initialCandidate = '' }: { user: User; refreshMS: number; initialRun?: string; initialCandidate?: string }) {
  const [tab, setTab] = useState(initialCandidate ? 'shadow' : 'runs');
  const [cursors, setCursors] = useState(['']);
  const after = cursors[cursors.length - 1];
  const runs = useGeneratedResource('analysis-runs:' + after, useCallback((signal: AbortSignal) => listAnalysisRuns(after, 100, signal), [after]), refreshMS);
  const candidates = useGeneratedResource('shadow-candidates', useCallback((signal: AbortSignal) => listShadowCandidates(signal), []), refreshMS);
  const definitions = useGeneratedResource('history-definitions', useCallback((signal: AbortSignal) => api<Definition[]>('/definitions', { signal }), []));
  const [selectedRun, setSelectedRun] = useState(initialRun);
  const [runInput, setRunInput] = useState(initialRun);
  const [selectedCandidate, setSelectedCandidate] = useState(initialCandidate);
  const [candidateInput, setCandidateInput] = useState(initialCandidate);
  useEffect(() => { setSelectedRun(initialRun); setRunInput(initialRun); }, [initialRun]);
  useEffect(() => { setSelectedCandidate(initialCandidate); setCandidateInput(initialCandidate); if (initialCandidate) setTab('shadow'); }, [initialCandidate]);
  const candidate = useGeneratedResource(selectedCandidate || null, useCallback((signal: AbortSignal) => getShadowCandidate(selectedCandidate, signal), [selectedCandidate]), refreshMS);
  const [creating, setCreating] = useState(false);
  const [historyForm, setHistoryForm] = useState(defaults);
  const [shadowOpen, setShadowOpen] = useState(false);
  const [shadowForm, setShadowForm] = useState({ id: '', definitionID: '', version: '1', devices: '', keys: '', initialState: '{}' });
  const [shadowExpected, setShadowExpected] = useState<ShadowCandidate['version']>(0);
  const [stopConfirmation, setStopConfirmation] = useState<ShadowCandidate>();
  const [busy, setBusy] = useState(false);
  const [formError, setFormError] = useState('');
  const [notice, setNotice] = useState<Notice>();
  useEffect(() => { setNotice(value => value?.kind === 'success' ? undefined : value); setStopConfirmation(undefined); }, [user.id, user.version, user.roles.join('|'), user.resources.join('|')]);
  const manage = !user.ai && user.roles.some(role => ['admin', 'engineer'].includes(role));
  const chooseCandidate = (id: string) => { setSelectedCandidate(id); setCandidateInput(id); setNotice(undefined); };
  const chooseRun = (id: string) => { setSelectedRun(id); setRunInput(id); };
  const failure = (error: unknown) => setNotice(error instanceof RequestError && error.status === 409
    ? { kind: 'warning', title: '候选版本已经变化', description: '详情已更新，请核对当前版本和采集状态。服务返回：' + error.message }
    : { kind: 'error', title: error instanceof RequestError && error.status === 403 ? '当前身份无权管理此候选' : '候选操作未完成', description: errorText(error) });
  const createRun = async () => {
    setBusy(true); setFormError('');
    try { const result = await createAnalysisRun(buildHistoryRequest(historyForm)); setCreating(false); chooseRun(result.id); runs.reload(); }
    catch (error) { setFormError(errorText(error)); definitions.reload(); runs.reload(); }
    finally { setBusy(false); }
  };
  const openShadow = (value?: ShadowCandidate) => {
    setFormError(''); setShadowExpected(value?.version ?? 0);
    setShadowForm(value ? { id: value.id, definitionID: value.definition_id ?? '', version: String(value.definition_version ?? 1), devices: (value.device_ids ?? []).join(', '), keys: (value.keys ?? []).join(', '), initialState: '{}' } : { id: '', definitionID: '', version: '1', devices: '', keys: '', initialState: '{}' });
    setShadowOpen(true);
  };
  const saveShadow = async () => {
    setBusy(true); setFormError(''); setNotice(undefined);
    try { const result = await saveShadowCandidate(buildShadowRequest(shadowForm, shadowExpected)); chooseCandidate(result.id); setNotice({ kind: 'success', id: result.id, title: '候选启用请求已保存' }); setShadowOpen(false); }
    catch (error) { setFormError(errorText(error)); failure(error); }
    finally { setBusy(false); candidate.reload(); candidates.reload(); definitions.reload(); }
  };
  const stop = async () => {
    if (!stopConfirmation) return;
    setBusy(true); setNotice(undefined);
    try { const result = await stopShadowCandidate(stopConfirmation); setNotice({ kind: 'success', id: result.id, title: '候选停止请求已保存' }); }
    catch (error) { failure(error); }
    finally { setBusy(false); setStopConfirmation(undefined); candidate.reload(); candidates.reload(); }
  };
  const updateHistory = <K extends keyof HistoryFormInput>(key: K, value: HistoryFormInput[K]) => setHistoryForm(previous => ({ ...previous, [key]: value }));
  const published = (definitions.data ?? []).filter(value => value.status === 'published').map(value => ({ value: value.id, label: `${value.name} · ${kindNames[value.kind] || value.kind}` }));
  const historyField = (label: string, key: keyof HistoryFormInput) => <Form.Item label={label}><Input aria-label={label} value={String(historyForm[key])} onChange={event => updateHistory(key, event.target.value as never)} /></Form.Item>;
  return <><PageTitle title="历史分析与影子计算" note="按保存的输入与历史规则分析结果，查看两侧计划、节点来源和候选与正式结果的差异。" actions={<Space><Button onClick={() => { runs.reload(); candidates.reload(); }}>更新分析记录</Button>{manage && <><Button onClick={() => { setFormError(''); setShadowOpen(false); openShadow(); }}>启用影子候选</Button><Button type="primary" onClick={() => { setFormError(''); setCreating(true); }}>创建历史分析</Button></>}</Space>} />
    <Tabs activeKey={tab} onChange={setTab} items={[
      { key: 'runs', label: '回放与比较运行', children: <><div className="query-toolbar"><Input aria-label="分析运行身份" placeholder="输入完整分析运行身份" value={runInput} onChange={event => setRunInput(event.target.value)} /><Button disabled={!runInput.trim()} onClick={() => chooseRun(runInput.trim())}>查看指定运行</Button></div>{runs.error && <Alert className="error-notice" type="error" showIcon title="分析列表读取未完成" description={runs.error} />}<Card><Table<HistoryRun> rowKey="id" dataSource={runs.data?.items ?? []} loading={runs.loading} pagination={false} scroll={{ x: 1100 }} columns={[
        { title: '运行 / 规则', render: (_, row) => <><Button type="link" onClick={() => chooseRun(row.id)}>{row.id}</Button><small className="table-subtext">{row.definition_id}</small></> }, { title: '分析类别', render: (_, row) => kindNames[row.kind ?? ''] || row.kind }, { title: '运行状态', render: (_, row) => <State value={row.status} /> }, { title: '计算进度', render: (_, row) => <><Progress percent={Math.round((row.progress ?? 0) * 100)} size="small" status={row.status === 'failed' ? 'exception' : row.status === 'completed' ? 'success' : 'active'} /><small className="table-subtext">已提交 {String(row.cursor ?? 0)} / {String(row.total ?? 0)} 条输入</small></> }, { title: '结果 / 原因', dataIndex: 'error' }, { title: '操作', render: (_, row) => <Button onClick={() => chooseRun(row.id)}>运行详情</Button> },
      ]} /><Space className="section-actions"><Button disabled={cursors.length <= 1} onClick={() => setCursors(value => value.slice(0, -1))}>上一页</Button><span>第{cursors.length}页</span><Button disabled={!runs.data?.next || runs.loading} onClick={() => { if (runs.data?.next) setCursors(value => [...value, runs.data!.next]); }}>下一页</Button></Space></Card></> },
      { key: 'shadow', label: '影子候选', children: <><div className="query-toolbar"><Input aria-label="影子候选身份" placeholder="输入完整影子候选身份" value={candidateInput} onChange={event => setCandidateInput(event.target.value)} /><Button disabled={!candidateInput.trim()} onClick={() => chooseCandidate(candidateInput.trim())}>查看指定候选</Button></div>{candidates.error && <Alert className="error-notice" type="error" showIcon title="候选列表读取未完成" description={candidates.error} />}<Card><Table<ShadowCandidate> rowKey="id" dataSource={candidates.data ?? []} loading={candidates.loading} scroll={{ x: 1100 }} columns={[
        { title: '候选 / 规则版本', render: (_, row) => <><Button type="link" onClick={() => chooseCandidate(row.id)}>{row.id}</Button><small className="table-subtext">{row.definition_id} · v{String(row.definition_version ?? '')}</small></> }, { title: '采集状态', render: (_, row) => <State value={row.status} /> }, { title: '采集轮次 / 管理版本', render: (_, row) => `${String(row.epoch)} / ${String(row.version)}` }, { title: '完成 / 采集代次', render: (_, row) => `${String(row.completed_generation ?? 0)} / ${String(row.generation ?? 0)}` }, { title: '最近运行', render: (_, row) => row.last_run_id ? <Button type="link" onClick={() => chooseRun(row.last_run_id!)}>{row.last_run_id}</Button> : '尚未产生运行' }, { title: '说明', dataIndex: 'error' }, { title: '操作', render: (_, row) => <Button onClick={() => chooseCandidate(row.id)}>候选详情</Button> },
      ]} /></Card></> },
    ]} />
    <Modal title="创建历史分析" open={creating && manage} width="min(820px, 95vw)" onCancel={() => setCreating(false)} onOk={() => void createRun()} confirmLoading={busy} okText="保存输入并开始分析"><Form layout="vertical">
      {formError && <Alert className="error-notice" type="error" showIcon title="分析请求未创建" description={formError} />}
      <div className="analysis-form-grid"><Form.Item label="分析类别"><Select aria-label="分析类别" value={historyForm.kind} onChange={value => updateHistory('kind', value)} options={[{ value: 'replay', label: '按当时生效版本回放' }, { value: 'compare', label: '比较两个已发布版本' }]} /></Form.Item><Form.Item label="已发布规则"><Select aria-label="历史分析规则" showSearch value={historyForm.definitionID || undefined} onChange={value => updateHistory('definitionID', value)} options={published} /></Form.Item>{historyField('运行身份（可留空）', 'id')}{historyField('设备范围（逗号分隔）', 'devices')}{historyField('开始时间（Unix毫秒）', 'from')}{historyField('结束时间（Unix毫秒）', 'to')}{historyField('测点范围（逗号分隔）', 'keys')}<Form.Item label="输入顺序"><Select aria-label="历史输入顺序" value={historyForm.order} onChange={value => updateHistory('order', value)} options={[{ value: 'event_time', label: '观测时间、来源序号和身份' }, { value: 'provided', label: '提供的数组顺序' }]} /></Form.Item>{historyForm.kind === 'compare' && <>{historyField('左侧规则版本', 'leftVersion')}{historyField('右侧规则版本', 'rightVersion')}</>}</div>
      <Form.Item label="分析输入来源"><Select aria-label="分析输入来源" value={historyForm.inputSource} onChange={value => updateHistory('inputSource', value)} options={[{ value: 'retained', label: '范围内的实际保留数据' }, { value: 'provided', label: '自行提供观测数组' }]} /></Form.Item>{historyForm.inputSource === 'provided' && <Form.Item label="观测数组（保留精确整数）"><Input.TextArea aria-label="历史观测数组" rows={5} value={historyForm.points} onChange={event => updateHistory('points', event.target.value)} /></Form.Item>}
      <Form.Item label="计算历史来源"><Select aria-label="计算历史来源" value={historyForm.historySource} onChange={value => updateHistory('historySource', value)} options={[{ value: 'retained', label: '读取实际窗口历史' }, { value: 'provided', label: '自行提供历史，[]表示空历史' }]} /></Form.Item>{historyForm.historySource === 'provided' && <Form.Item label="历史数组"><Input.TextArea aria-label="计算历史数组" rows={3} value={historyForm.history} onChange={event => updateHistory('history', event.target.value)} /></Form.Item>}
      <Form.Item label="时钟、初始状态和资产版本（可选JSON）"><Input.TextArea aria-label="历史计算条件" rows={4} value={historyForm.parameters} onChange={event => updateHistory('parameters', event.target.value)} /></Form.Item><p>所有时间和间隔均为Unix毫秒或毫秒；每份运行最多10000条输入、40000条历史和32MiB快照，提交后采用保存的输入条件。</p>
    </Form></Modal>
    <Modal title={shadowExpected === 0 ? '启用影子候选' : '重新启用候选'} open={shadowOpen && manage} zIndex={1200} onCancel={() => setShadowOpen(false)} onOk={() => void saveShadow()} confirmLoading={busy} okText="保存并开始采集"><Form layout="vertical">{formError && <Alert className="error-notice" type="error" showIcon title="候选请求未保存" description={formError} />}<Form.Item label="候选身份"><Input aria-label="新候选身份" disabled={shadowExpected !== 0} value={shadowForm.id} onChange={event => setShadowForm(value => ({ ...value, id: event.target.value }))} /></Form.Item><Form.Item label="已发布规则"><Select aria-label="影子规则" value={shadowForm.definitionID || undefined} options={published} onChange={value => setShadowForm(previous => ({ ...previous, definitionID: value }))} /></Form.Item>{(['version', 'devices', 'keys'] as const).map(key => <Form.Item key={key} label={{ version: '候选规则版本', devices: '候选设备范围', keys: '候选测点范围' }[key]}><Input aria-label={{ version: '候选规则版本', devices: '候选设备范围', keys: '候选测点范围' }[key]} value={shadowForm[key]} onChange={event => setShadowForm(value => ({ ...value, [key]: event.target.value }))} /></Form.Item>)}<Form.Item label="候选初始状态"><Input.TextArea aria-label="候选初始状态" rows={4} value={shadowForm.initialState} onChange={event => setShadowForm(value => ({ ...value, initialState: event.target.value }))} /></Form.Item><p>保存后建立新的采集轮次，原有运行和输入回执继续保留；候选计算结果可以沿运行身份查询。</p></Form></Modal>
    <Drawer title="影子候选详情" open={!!selectedCandidate} width="min(850px, 100vw)" extra={<Button onClick={candidate.reload} loading={candidate.loading}>更新候选详情</Button>} onClose={() => { chooseCandidate(''); if (initialCandidate) location.hash = 'history'; }}>
      {notice?.kind !== 'success' && notice && <Alert className="error-notice" type={notice.kind} showIcon title={notice.title} description={notice.description} />}
      {candidate.error && <Alert type="error" showIcon title="候选详情读取未完成" description={candidate.error} />}
      {candidate.data && <div data-testid="shadow-candidate-detail">{notice?.kind === 'success' && notice.id === candidate.data.id && <Alert className="error-notice" showIcon type="success" title={notice.title} description={historyStatusText(candidate.data.status)} />}<Descriptions bordered size="small" column={1} items={[
        { key: 'id', label: '候选身份', children: candidate.data.id }, { key: 'rule', label: '候选规则版本', children: `${candidate.data.definition_id} · v${String(candidate.data.definition_version)}` }, { key: 'state', label: '当前采集状态', children: <State value={candidate.data.status} /> }, { key: 'version', label: '管理版本 / 采集轮次', children: `${String(candidate.data.version)} / ${String(candidate.data.epoch)}` }, { key: 'progress', label: '完成 / 已采集代次', children: `${String(candidate.data.completed_generation ?? 0)} / ${String(candidate.data.generation ?? 0)}` }, { key: 'inputs', label: '当前有效输入数量', children: String(candidate.data.input_count ?? 0) }, { key: 'devices', label: '设备 / 测点', children: `${(candidate.data.device_ids ?? []).join('、')} / ${(candidate.data.keys ?? []).join('、')}` }, { key: 'latest', label: '最新完成运行', children: candidate.data.last_run_id ? <Button onClick={() => chooseRun(candidate.data!.last_run_id!)}>{candidate.data.last_run_id}</Button> : '尚未完成运行' }, { key: 'started', label: '开始 / 停止时间', children: `${exactTimestamp(candidate.data.started_ms)} / ${exactTimestamp(candidate.data.stopped_ms)}` }, { key: 'error', label: '采集说明', children: candidate.data.error || '暂无错误' },
      ]} /><Space className="section-actions">{manage && <>{candidate.data.status === 'active' && <Button danger disabled={busy} onClick={() => setStopConfirmation(candidate.data)}>停止后续采集</Button>}<Button disabled={busy} onClick={() => openShadow(candidate.data)}>重新启用候选</Button></>}<Button onClick={() => download('shadow-candidate.json', candidate.data)}>导出候选详情</Button></Space><Collapse className="section-card" items={[{ key: 'latest', label: '最新观测及输入来源', children: <pre className="json-view">{json(candidate.data.last_input)}</pre> }, { key: 'context', label: '当前字段上下文', children: <pre className="json-view">{json(candidate.data.context)}</pre> }, { key: 'base', label: '采集轮次保存的基础快照', children: <pre className="json-view">{json(candidate.data.base_snapshot)}</pre> }]} /></div>}
    </Drawer>
    <Modal title="停止后续影子采集" open={!!stopConfirmation && !!candidate.data} onCancel={() => setStopConfirmation(undefined)} onOk={() => void stop()} confirmLoading={busy} okText="停止采集"><p>停止新的观测采集，已经创建的分析运行继续保留，可以通过对应后台任务查看或取消后续计算。</p><p>候选：{stopConfirmation?.id}；此次管理版本：{String(stopConfirmation?.version ?? '')}</p></Modal>
    <RunDetail id={selectedRun} refreshMS={refreshMS} onClose={() => { chooseRun(''); if (initialRun) location.hash = 'history'; }} />
  </>;
}

function RunDetail({ id, refreshMS, onClose }: { id: string; refreshMS: number; onClose: () => void }) {
  const detail = useGeneratedResource(id || null, useCallback((signal: AbortSignal) => getAnalysisRun(id, signal), [id]), refreshMS);
  const [tab, setTab] = useState('overview');
  const [positions, setPositions] = useState([0]);
  const [selectedIndex, setSelectedIndex] = useState<number>();
  useEffect(() => { setTab('overview'); setPositions([0]); setSelectedIndex(undefined); }, [id]);
  const after = positions[positions.length - 1];
  const steps = useGeneratedResource(id && detail.data ? `${id}:steps:${after}` : null, useCallback((signal: AbortSignal) => getAnalysisSteps(id, after, 100, signal), [id, after]), refreshMS);
  const snapshot = useGeneratedResource(id && detail.data && tab === 'snapshot' ? `${id}:snapshot:${detail.data.snapshot_id}` : null, useCallback((signal: AbortSignal) => getAnalysisSnapshot(id, signal), [id]));
  const taskID = detail.data?.task_id ?? '';
  const task = useGeneratedResource(taskID || null, useCallback((signal: AbortSignal) => getTask(taskID, signal), [taskID]), refreshMS);
  const run = detail.data;
  const step = steps.data?.items.find(value => Number(value.input_index) === selectedIndex);
  const refresh = () => { detail.reload(); steps.reload(); snapshot.reload(); task.reload(); };
  return <><Drawer title="历史分析运行详情" open={!!id} width="min(1200px, 100vw)" onClose={onClose} extra={<Button onClick={refresh} loading={detail.loading}>更新运行详情</Button>}>
    {detail.error && <Alert showIcon type="error" title="运行详情读取未完成" description={detail.error} />}
    {run && <div data-testid="history-run-detail"><Descriptions bordered size="small" column={{ xs: 1, sm: 2 }} items={[
      { key: 'id', label: '运行身份', children: run.id }, { key: 'kind', label: '分析类别 / 规则', children: `${kindNames[run.kind ?? ''] || run.kind} / ${run.definition_id}` }, { key: 'status', label: '运行状态', children: <State value={run.status} /> }, { key: 'error', label: '处理原因', children: run.error || '暂无错误' }, { key: 'versions', label: '左侧 / 右侧规则版本', children: `${String(run.left_version ?? '按观测时刻选择')} / ${String(run.right_version ?? '未指定')}` }, { key: 'snapshot', label: '实际计算快照身份', children: run.snapshot_id }, { key: 'captured', label: '入口采集快照身份', children: run.captured_snapshot_id }, { key: 'resolved', label: '初始状态是否已解析', children: run.initial_state_resolved ? '已解析并保存' : run.parent_run_id ? '等待前序状态' : '使用保存的初始状态' }, { key: 'parent', label: '前序运行', children: run.parent_run_id || '未关联前序运行' }, { key: 'input', label: '共同输入条件摘要', children: run.input_sha256 }, { key: 'sha', label: '实际快照内容摘要', children: run.snapshot_sha256 }, { key: 'progress', label: '已提交输入 / 总数', children: `${String(run.cursor ?? 0)} / ${String(run.total ?? 0)}` },
    ]} /><Progress className="section-actions" percent={Math.round((run.progress ?? 0) * 100)} status={run.status === 'completed' ? 'success' : run.status === 'failed' ? 'exception' : 'active'} />
    {run.status === 'waiting_parent' && <Alert className="error-notice" showIcon type="warning" title="等待前序影子计算完成" description="前序完成后将保存实际采用的初始状态快照，再继续此次输入。" />}
    <Card size="small" title="关联后台任务" className="section-card">{task.error && <Alert type="error" showIcon title="任务详情读取未完成" description={task.error} />}{task.data && <Descriptions column={1} items={[{ key: 'id', label: '任务身份', children: task.data.id }, { key: 'phase', label: '当前任务状态', children: `${taskStateText(task.data.state)} · ${taskPhaseText(task.data)}` }, { key: 'attempt', label: '尝试次数 / 下次时间', children: `${String(task.data.attempt ?? 0)} / ${String(task.data.max_attempts ?? 0)} · ${exactTimestamp(task.data.next_ms)}` }, { key: 'error', label: '最近失败', children: task.data.error || '暂无失败' }]} />}<Button onClick={() => { location.hash = 'tasks?task=' + encodeURIComponent(run.task_id); }}>查看任务详情与许可操作</Button></Card>
    <Tabs activeKey={tab} onChange={setTab} items={[
      { key: 'overview', label: '逐点结果与差异', children: <>{steps.error && <Alert className="error-notice" type="error" showIcon title="逐点结果读取未完成" description={steps.error} />}<Table<HistoryStep> rowKey={row => row.id ?? String(row.input_index)} size="small" pagination={false} dataSource={steps.data?.items ?? []} loading={steps.loading} scroll={{ x: 1200 }} columns={[
        { title: '输入序号 / 原观测身份', render: (_, row) => <>{String(row.input_index ?? 0)}<small className="table-subtext">{row.point?.id}</small></> }, { title: '设备 / 测点 / 原始值', render: (_, row) => <>{row.point?.device_id} / {row.point?.key}<pre className="analysis-value">{json(row.point?.value)}</pre></> }, { title: '观测 / 逻辑时钟', render: (_, row) => <>{exactTimestamp(row.point?.observed_ms)}<small className="table-subtext">{exactTimestamp(row.clock_ms)}<br />新鲜度：{exactTimestamp(row.freshness_at_ms)}</small></> }, { title: '质量 / 来源 / 修订', render: (_, row) => <>{row.point?.quality}<small className="table-subtext">{row.point?.source_id} / r{String(row.point?.revision ?? 0)}<br />{row.point?.late ? '迟到观测' : '按时观测'}</small></> }, { title: '采用版本 / 各侧结果', render: (_, row) => row.lanes?.map(lane => <div key={lane.side}><strong>{lane.side === 'left' ? '左侧' : lane.side === 'right' ? '右侧' : '回放/候选'} · v{String(lane.definition_version)}</strong><pre className="analysis-value">{lane.skipped || json(lane.evaluation?.values)}</pre></div>) }, { title: run.kind === 'compare' ? '两版本差异' : run.kind === 'shadow' ? '正式与候选差异' : '本次回放结果', render: (_, row) => historyComparisonText(run.kind, row) }, { title: '节点与来源', render: (_, row) => <Button onClick={() => setSelectedIndex(Number(row.input_index ?? 0))}>解释此输入</Button> },
      ]} /><Space wrap className="section-actions"><Button disabled={positions.length <= 1} onClick={() => setPositions(value => value.slice(0, -1))}>上一页结果</Button><span>本页从第{after}条输入开始，显示{steps.data?.items.length ?? 0}条{steps.data?.next === -1 ? '，已读到当前可用结果末尾' : ''}</span><Button disabled={steps.loading || !steps.data || steps.data.next < 0} onClick={() => { if (steps.data && steps.data.next >= 0) setPositions(value => [...value, steps.data!.next]); }}>下一页结果</Button><Button disabled={!steps.data} onClick={() => download('history-results-page.json', { run, after, next: steps.data?.next, items: steps.data?.items })}>导出本页结果（精确JSON）</Button></Space></> },
      { key: 'snapshot', label: '输入与历史快照', children: <>{snapshot.error && <Alert className="error-notice" type="error" showIcon title="快照读取未完成" description={snapshot.error} />}{snapshot.data && <><Descriptions bordered column={1} size="small" items={[
        { key: 'source', label: '保存来源 / 数据版本', children: `${snapshot.data.source} / ${String(snapshot.data.data_version)}` }, { key: 'scope', label: '实际范围', children: `${exactTimestamp(snapshot.data.from_ms)} 至 ${exactTimestamp(snapshot.data.to_ms)}` }, { key: 'order', label: '排序 / 时钟', children: <>{snapshot.data.order === 'provided' ? '提供的数组顺序' : '观测时间、来源序号和身份'}<pre className="analysis-value">{json(snapshot.data.clock)}</pre></> }, { key: 'integrity', label: '保留数据完整程度 / 缺口', children: `${snapshot.data.completeness || '未提供'} / ${snapshot.data.data_gaps?.length ?? 0}段` }, { key: 'input', label: '输入 / 历史条数', children: `${snapshot.data.points?.length ?? 0} / ${snapshot.data.history?.length ?? 0}` }, { key: 'sourceState', label: '初始状态来源 / 前序运行', children: `${snapshot.data.initial_state_source} / ${snapshot.data.initial_state_run_id || '未关联'}` }, { key: 'sha', label: '完整快照 / 输入 / 历史摘要', children: <>{snapshot.data.sha256}<small className="table-subtext">{snapshot.data.input_sha256}<br />{snapshot.data.history_sha256}</small></> },
      ]} /><Button className="section-actions" onClick={() => download('history-snapshot.json', { run, snapshot: snapshot.data })}>导出保存的完整快照（精确JSON）</Button><Collapse className="section-card" items={[{ key: 'points', label: '实际排序后的输入观测', children: <pre className="json-view">{json(snapshot.data.points)}</pre> }, { key: 'history', label: '实际采用的计算历史', children: <pre className="json-view">{json(snapshot.data.history)}</pre> }, { key: 'rules', label: '历史规则、生效时间和持久计划', children: <pre className="json-view">{json(snapshot.data.rules)}</pre> }, { key: 'assets', label: '设备和祖先资产版本', children: <pre className="json-view">{json(snapshot.data.asset_versions)}</pre> }, { key: 'state', label: '实际初始节点状态', children: <pre className="json-view">{json(snapshot.data.initial_state)}</pre> }, { key: 'gaps', label: '数据缺口与完整性记录', children: <pre className="json-view">{json(snapshot.data.data_gaps)}</pre> }]} /></>}</> },
    ]} />
    </div>}
  </Drawer><Drawer title="节点计算与来源解释" open={!!step && !!run} width="min(1100px, 100vw)" onClose={() => setSelectedIndex(undefined)}>
    {step && run && <div data-testid="history-node-explanation"><Descriptions column={1} items={[{ key: 'identity', label: '运行 / 输入身份', children: `${step.run_id} / ${step.point?.id}` }, { key: 'input', label: '当前输入内容摘要', children: step.input_sha256 }, { key: 'origin', label: '来源 / 原始数值 / 单位', children: <>{step.point?.source_id}<pre className="analysis-value">{json(step.point?.value)}</pre>{step.point?.unit || '未记录单位'}</> }, { key: 'clock', label: '观测 / 逻辑 / 新鲜度时刻', children: `${exactTimestamp(step.point?.observed_ms)} / ${exactTimestamp(step.clock_ms)} / ${exactTimestamp(step.freshness_at_ms)}` }]} />
    {(step.lanes ?? []).map(lane => <Card className="section-card" key={lane.side} title={`${lane.side === 'left' ? '左侧' : lane.side === 'right' ? '右侧' : '回放/候选'}计划 · v${String(lane.definition_version)}`}><Descriptions column={1} items={[{ key: 'plan', label: '计划身份 / 内容摘要', children: <>{lane.plan_id}<small className="table-subtext">{lane.plan_sha256}</small></> }, { key: 'effective', label: '规则生效时刻', children: exactTimestamp(lane.effective_ms) }, { key: 'inputs', label: '采用的输入观测身份', children: (lane.evaluation?.input_ids ?? []).join('、') || '未记录输入' }, { key: 'result', label: '计算结果 / 质量', children: <pre className="json-view">{json({ values: lane.evaluation?.values, quality: lane.evaluation?.quality, trigger: lane.evaluation?.trigger, alarm: lane.evaluation?.alarm })}</pre> }, { key: 'skipped', label: '跳过原因', children: lane.skipped || '此次输入执行计算' }]} /><Table<Contract<'NodeTrace'>> size="small" rowKey={row => row.node_id ?? ''} pagination={false} scroll={{ x: 850 }} dataSource={lane.evaluation?.trace ?? []} columns={[
      { title: '节点 / 类型', render: (_, row) => <>{row.node_id}<small className="table-subtext">{row.type}</small></> }, { title: '节点输入', render: (_, row) => <pre className="analysis-value">{json(row.input)}</pre> }, { title: '节点输出', render: (_, row) => <pre className="analysis-value">{json(row.output)}</pre> }, { title: '处理结果', render: (_, row) => row.error || (row.skipped ? '已跳过' : '已执行') },
    ]} expandable={{ expandedRowRender: row => <div className="analysis-lanes"><Card size="small" title="计算前状态"><pre className="json-view">{json(row.before)}</pre></Card><Card size="small" title="计算后状态"><pre className="json-view">{json(row.after)}</pre></Card></div> }} /><Collapse className="section-card" items={[{ key: 'asset', label: '此次采用的资产版本与生效时间', children: <pre className="json-view">{json(lane.evaluation?.asset_versions)}</pre> }, { key: 'intent', label: '此次候选产生的步骤意图', children: <pre className="json-view">{json(lane.action_intents)}</pre> }]} /></Card>)}
    {run.kind === 'shadow' && <Card className="section-card" title="与对应正式结果比较"><Descriptions column={1} items={[{ key: 'status', label: '正式来源', children: formalStatusText(step.formal_status) }, { key: 'id', label: '正式输入 / 正式补算身份', children: `${step.formal_input_id || '暂无对应输入'} / ${step.formal_evaluation?.run_id || '未关联补算'}` }, { key: 'plan', label: '正式计划身份 / 版本', children: `${step.formal_evaluation?.plan_id || '暂无对应计划'} / ${String(step.formal_evaluation?.version ?? '未提供')}` }, { key: 'difference', label: '正式与候选差异', children: historyComparisonText('shadow', step) }]} /><Collapse items={[{ key: 'formal', label: '正式求值、输入来源和节点解释', children: <pre className="json-view">{json(step.formal_evaluation)}</pre> }, { key: 'outputs', label: '当前正式派生值、观测修订和来源', children: <pre className="json-view">{json(step.formal_outputs)}</pre> }]} /></Card>}
    </div>}
  </Drawer></>;
}
