import { useEffect, useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Alert, Button, Card, Descriptions, Drawer, Form, Input, Select, Space, Table, Tag } from 'antd';
import { json, timestamp, useResource, RequestError } from './api';
import { callOperation, type Contract } from './generated-client';
import { useRetainedEdit } from './editor-state';
import { ErrorNotice, PageTitle } from './views';
import type { User } from './types';
import { actionReason, releaseActions, releaseStates, releaseContentDigest, publicConnectorDigest, replaceProgram, reportTiming, workloadIssues } from './release-state';

type Basis = { id: string; version: Contract<'ReleaseDeployment'>['version']; reason: string; oldRelease: string; rollbackID: string };
const emptyBasis: Basis = { id: '', version: 0, reason: '', oldRelease: '', rollbackID: '' };
export function Releases({ user, mode, refreshMS, initialID = '', initialRelease = '' }: { user: User; mode: string; refreshMS: number; initialID?: string; initialRelease?: string }) {
  const mayCreate = mode === 'cloud' && (user.roles.includes('admin') || user.roles.includes('engineer'));
  const interval = refreshMS === 0 ? 0 : Math.min(refreshMS > 0 ? refreshMS : 1000, 5000);
  const releases = useResource<Contract<'Release'>[]>('/releases', interval);
  const definitions = useResource<Contract<'Definition'>[]>(mayCreate ? '/definitions' : null);
  const parameters = useResource<Contract<'Parameter'>[]>(mayCreate && user.roles.includes('admin') ? '/config' : null);
  const connectors = useResource<Contract<'ConnectorConfigurationDetail'>[]>(mayCreate ? '/connector-configurations' : null);
  const [sourceComponents, setSourceComponents] = useState<Contract<'ReleaseComponent'>[]>([]);
  const artifacts = useResource<Contract<'ReleaseArtifact'>[]>(mayCreate ? '/release-artifacts' : null);
  const identities = useResource<Contract<'WorkloadIdentity'>[]>('/workload-identities', interval);
  const deployments = useResource<Contract<'ReleaseDeployment'>[]>('/release-deployments', interval);
  const [selected, setSelected] = useState(initialID);
  useEffect(() => { setSelected(initialID); }, [initialID]);
  const detail = useResource<Contract<'ReleaseDeployment'>>(selected ? '/release-deployments/' + encodeURIComponent(selected) : null, interval);
  const reports = useResource<Contract<'ReleaseNodeReport'>[]>(selected ? '/release-deployments/' + encodeURIComponent(selected) + '/reports' : null, interval);
  const [basis, setBasis] = useRetainedEdit<Basis>('release-action', emptyBasis);
  const [now, setNow] = useState(Date.now());
  const [compose, setCompose] = useState(false);
  const [manifest, setManifest] = useRetainedEdit<Contract<'ReleaseManifest'> | null>('release-manifest', null);
  const [validation, setValidation] = useState<{ input: string; value: Contract<'ReleaseValidation'> }>();
  const [deployOpen, setDeployOpen] = useState(false);
  const [request, setRequest] = useRetainedEdit<Contract<'CreateReleaseDeploymentInput'>>('release-create-deployment', { id: '', request_id: '', release_id: '', group_id: 'factory', batches: [[]], reason: '' });
  useEffect(() => { if (initialRelease) { setRequest(previous => ({ ...previous, release_id: initialRelease, id: previous.id || 'deploy-' + crypto.randomUUID(), request_id: crypto.randomUUID(), batches: [[]] })); setDeployOpen(true); } }, [initialRelease]);
  const [nodeFilter, setNodeFilter] = useState('');
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { if (detail.data && basis.id !== detail.data.id) setBasis({ ...emptyBasis, id: detail.data.id ?? '', version: detail.data.version, rollbackID: 'rollback-' + crypto.randomUUID() }); }, [detail.data, basis.id]);
  useEffect(() => {
    let current = true;
    const read = async () => {
      const rules = await Promise.all((definitions.data ?? []).filter(definition => definition.status === 'published').map(async definition => ({ id: definition.id ?? '', kind: 'rule' as const, version: String(definition.version), sha256: await releaseContentDigest(definition), format: definition.schema_version || '1.0', content: definition })));
      const configs: Contract<'ReleaseComponent'>[] = (parameters.data ?? []).filter(parameter => !!parameter.content_digest).map(parameter => ({ id: 'parameter:' + parameter.id, kind: 'configuration', version: String(parameter.version), sha256: parameter.content_digest!, format: 'smartfactory-configuration-v1', target_node_ids: parameter.target_node_ids, configuration: { kind: 'parameter', id: parameter.id, version: parameter.version, digest: parameter.content_digest! } }));
      for (const connector of connectors.data ?? []) {
        const configuration = connector.configuration;
        if (!configuration?.id || !configuration.edge_id || !configuration.version) continue;
        const digest = await publicConnectorDigest(configuration);
        configs.push({ id: 'connector:' + configuration.id, kind: 'configuration', version: String(configuration.version), sha256: digest, format: 'smartfactory-configuration-v1', target_node_ids: [configuration.edge_id], required_capabilities: ['connector:' + configuration.protocol], configuration: { kind: 'connector', id: configuration.id, version: configuration.version, digest } });
      }
      if (current) setSourceComponents([...rules, ...configs]);
    };
    void read(); return () => { current = false; };
  }, [definitions.data, parameters.data, connectors.data, releases.data]);
  const availableComponents = [...sourceComponents, ...releases.data?.flatMap(item => item.manifest?.components ?? []) ?? []];
  const refresh = async () => { await Promise.all([releases.reload(), identities.reload(), definitions.reload(), parameters.reload(), connectors.reload(), deployments.reload(), detail.reload(), reports.reload()]); };
  const openDetail = (id: string) => { setSelected(id); location.hash = 'releases?deployment=' + encodeURIComponent(id); };
  const validate = useMutation({ mutationFn: async () => {
    if (!manifest) throw new Error('请创建发布清单，并选择程序、规则和配置');
    const input = json(manifest); const value = await callOperation('post_releases_validate', { body: manifest }, { exact: true }); setValidation({ input, value }); return value;
  } });
  const save = useMutation({ mutationFn: async () => {
    if (!manifest || !validation?.value.valid || validation.input !== json(manifest)) throw new Error('请按当前组件完成清单校验');
    const saved = await callOperation('post_releases', { body: { request_id: crypto.randomUUID(), manifest } }, { exact: true });
    await releases.reload(); setCompose(false); setManifest(null); setValidation(undefined); return saved;
  } });
  const deploy = useMutation({ mutationFn: async () => {
    if (!request.id.trim() || !request.reason.trim() || !request.release_id || !request.batches?.every(batch => batch?.length)) throw new Error('请填写发布身份、原因，并为每个批次选择节点身份');
    const result = await callOperation('post_release_deployments', { body: { ...request, request_id: request.request_id || crypto.randomUUID() } }, { exact: true });
    setDeployOpen(false); await deployments.reload(); openDetail(result.id ?? ''); return result;
  } });
  const action = useMutation({ mutationFn: async (name: 'pause' | 'resume' | 'retry' | 'cancel' | 'rollback') => {
    if (!detail.data || basis.id !== detail.data.id || !basis.version || !basis.reason.trim()) throw new Error('请填写处理原因，并核对已阅业务版本');
    if (!detail.data.allowed_actions?.some(item => item.action === name && item.allowed)) throw new Error('当前身份和状态未允许此操作');
    const result = name === 'rollback'
      ? await callOperation('post_release_deployments_id_rollback', { parameters: { path: { id: basis.id } }, body: { id: basis.rollbackID, request_id: crypto.randomUUID(), expected_version: basis.version, release_id: basis.oldRelease, reason: basis.reason } }, { exact: true })
      : await callOperation('post_release_deployments_id_actions', { parameters: { path: { id: basis.id } }, body: { request_id: crypto.randomUUID(), expected_version: basis.version, action: name, reason: basis.reason } }, { exact: true });
    setBasis(previous => previous.id === basis.id ? { ...previous, id: result.id ?? basis.id, version: result.version } : previous); if (name === 'rollback') openDetail(result.id ?? ''); await refresh(); return result;
  } });
  const chosen = releases.data?.find(item => item.id === request.release_id);
  const nodeOptions = (identities.data ?? []).filter(identity => !nodeFilter || [identity.node_id, identity.id, identity.program, identity.purpose].some(value => value.includes(nodeFilter))).map(identity => {
    const issues = chosen?.manifest ? workloadIssues(identity, chosen.manifest) : ['请选择固定发布'];
    return { value: identity.id, label: `${identity.node_id} / ${identity.id} / ${identity.program} / ${identity.purpose}${issues.length ? '（' + issues.join('；') + '）' : ''}`, disabled: !!issues.length };
  });
  return <><PageTitle title="云边发布" note="将固定程序、规则和配置按节点身份分批启用，核对实际程序与消费者报告。" actions={<Space wrap><Button onClick={() => void refresh()}>更新发布状态</Button><Button disabled={!mayCreate} onClick={() => { setCompose(true); save.reset(); validate.reset(); }}>组合固定发布</Button><Button type="primary" disabled={!mayCreate} onClick={() => { setDeployOpen(true); deploy.reset(); if (!request.id) setRequest({ ...request, id: 'deploy-' + crypto.randomUUID(), request_id: crypto.randomUUID() }); }}>新建节点批次</Button></Space>} />
    <ErrorNotice error={releases.error || definitions.error || parameters.error || connectors.error || identities.error || deployments.error || detail.error || reports.error} retry={() => void refresh()} />
    {mode !== 'cloud' && <Alert type="info" title="此节点显示已同步的发布记录" description="节点批次与身份由云端权威服务处理；现场工作台继续展示本地实际状态。" />}
    <Card title="固定发布清单"><Table<Contract<'Release'>> rowKey="id" dataSource={releases.data ?? []} scroll={{ x: 950 }} expandable={{ expandedRowRender: item => <ManifestDetails manifest={item.manifest} digest={item.sha256} order={item.order} /> }} columns={[{ title: '发布名称', render: (_, item) => <>{item.manifest?.name}<small className="table-subtext">{item.id}</small></> }, { title: '程序', dataIndex: ['manifest', 'program'] }, { title: '组件数', render: (_, item) => item.manifest?.components?.length ?? 0 }, { title: '固定摘要', dataIndex: 'sha256', render: value => <code className="release-digest">{value}</code> }, { title: '登记时间', dataIndex: 'created_ms', render: value => timestamp(Number(value)) }]} /></Card>
    <Card title="节点发布批次" className="section-card"><Table rowKey="id" loading={deployments.loading} dataSource={deployments.data ?? []} scroll={{ x: 900 }} columns={[{ title: '批次身份', dataIndex: 'id' }, { title: '发布清单', dataIndex: 'release_id' }, { title: '业务版本', render: (_, item) => String(item.version) }, { title: '历史发布状态', dataIndex: 'state', render: value => releaseStates[value] ?? value }, { title: '当前批次', render: (_, item) => Number(item.current_batch ?? 0) + 1 }, { title: '目标节点', render: (_, item) => item.targets?.map(target => target.node_id).join('、') }, { title: '操作', render: (_, item) => <Button onClick={() => openDetail(item.id ?? '')}>查看节点与人工处理</Button> }]} /></Card>
    {detail.data && <Card title={'发布详情：' + detail.data.id} className="section-card" data-testid="release-detail"><Descriptions column={{ xs: 1, md: 2 }} items={[{ key: 'state', label: '历史发布状态', children: releaseStates[detail.data.state ?? ''] ?? detail.data.state }, { key: 'version', label: '当前业务版本', children: String(detail.data.version) }, { key: 'source', label: '固定发布', children: detail.data.release_id }, { key: 'rollback', label: '退回来源', children: detail.data.rollback_of || '此批次为直接发布' }, { key: 'reason', label: '发布原因', children: detail.data.reason }]} />
      <Table rowKey="index" dataSource={detail.data.batches ?? []} pagination={false} scroll={{ x: 850 }} columns={[{ title: '批次', render: (_, batch) => Number(batch.index ?? 0) + 1 }, { title: '工作负载身份', render: (_, batch) => batch.identity_ids?.join('、') }, { title: '状态', render: (_, batch) => releaseStates[batch.state ?? ''] ?? batch.state }, { title: '进入条件', dataIndex: 'entry_condition' }, { title: '进入 / 完成时间', render: (_, batch) => `${timestamp(Number(batch.entered_ms))} / ${timestamp(Number(batch.completed_ms))}` }]} />
      <Table className="section-card" rowKey="identity_id" dataSource={detail.data.targets ?? []} pagination={false} scroll={{ x: 1400 }} expandable={{ expandedRowRender: target => <><Descriptions column={{ xs: 1, md: 2 }} items={[{ key: 'pid', label: '实际程序 PID / 实例', children: `${String(target.runtime?.pid ?? 0)} / ${target.runtime?.process_instance_id || '暂无运行报告'}` }, { key: 'agent', label: '代理实例 / 代次', children: `${target.agent_instance_id || '暂无记录'} / ${String(target.agent_instance_epoch ?? 0)}` }, { key: 'build', label: '实际程序构建', children: `${target.runtime?.build?.version || '暂无记录'} / ${target.runtime?.build?.goos || ''} / ${target.runtime?.build?.goarch || ''}` }, { key: 'migration', label: '实际数据库迁移版本', children: String(target.runtime?.migration_version ?? 0) }, { key: 'sha', label: '实际程序摘要', children: <code>{target.runtime?.program_sha256 || '暂无报告'}</code> }, { key: 'policy', label: '实际消费者策略摘要', children: <code>{target.runtime?.policy_sha256 || '暂无报告'}</code> }]} /><Table rowKey="id" size="small" dataSource={target.runtime?.components ?? []} pagination={false} scroll={{ x: 1100 }} columns={[{ title: '组件', dataIndex: 'id' }, { title: '固定来源版本', dataIndex: 'version' }, { title: '固定来源摘要', dataIndex: 'sha256', render: value => <code className="release-digest">{value}</code> }, { title: '本地应用版本 / 代次', render: (_, item) => String(item.applied_version) }, { title: '实际应用摘要', dataIndex: 'applied_sha256', render: value => <code className="release-digest">{value}</code> }]} /></> }} columns={[{ title: '节点 / 身份', render: (_, target) => <>{target.node_id}<small className="table-subtext">{target.identity_id} / 第 {Number(target.batch ?? 0) + 1} 批 / 分配代次 {String(target.generation)}</small></> }, { title: '当前节点状态', render: (_, target) => <Tag color={target.state === 'failed' ? 'error' : reportTiming(target, now).fresh ? 'success' : 'warning'}>{releaseStates[target.state ?? ''] ?? target.state}</Tag> }, ...(['desired_sha256', 'prepared_sha256', 'applied_sha256', 'running_sha256'] as const).map((field, index) => ({ title: ['期望摘要', '准备摘要', '应用摘要', '运行摘要'][index], dataIndex: field, render: (value: string) => <code className="release-digest">{value || '尚未确认'}</code> })), { title: '实际报告时效', render: (_, target) => { const timing = reportTiming(target, now); return <div data-testid={'report-fresh-' + target.identity_id}><Tag color={timing.fresh ? 'success' : 'warning'}>{timing.fresh ? '实际报告有效' : '实际报告已过期或缺失'}</Tag><small className="table-subtext">{timing.age === null ? '暂无报告' : (timing.age / 1000).toFixed(1) + ' 秒 / 15 秒阈值'}</small></div>; } }, { title: '最后代理联系', render: (_, target) => timestamp(Number(target.last_seen_ms)) }, { title: '最后实际程序报告', render: (_, target) => timestamp(Number(target.last_report_ms)) }, { title: '失败组件 / 处理事项', render: (_, target) => <>{target.failure_component || ''}<p>{target.reason}</p></> }]} />
      <div className="release-action"><h3>人工处理</h3><p>已阅业务版本 {String(basis.version)}；页面持续更新节点状态，处理原因和旧发布选择保留在当前身份下。</p><Form layout="vertical"><Form.Item label="发布处理原因" required><Input.TextArea aria-label="发布处理原因" value={basis.reason} onChange={event => setBasis({ ...basis, reason: event.target.value })} rows={3} /></Form.Item><Form.Item label="退回的固定发布"><Select aria-label="退回的固定发布" value={basis.oldRelease || undefined} onChange={value => setBasis({ ...basis, oldRelease: value })} showSearch optionFilterProp="label" options={(releases.data ?? []).filter(item => item.id !== detail.data?.release_id).map(item => ({ value: item.id, label: `${item.manifest?.name} / ${item.id}` }))} /></Form.Item><Form.Item label="退回批次身份"><Input aria-label="退回批次身份" value={basis.rollbackID} onChange={event => setBasis({ ...basis, rollbackID: event.target.value })} /></Form.Item></Form>
      <Space wrap>{detail.data.allowed_actions?.map(item => <span key={item.action}><Button loading={action.isPending} disabled={!item.allowed || !basis.reason.trim() || (item.action === 'rollback' && (!basis.oldRelease || !basis.rollbackID.trim()))} onClick={() => action.mutate(item.action as 'pause' | 'resume' | 'retry' | 'cancel' | 'rollback')}>{releaseActions[item.action ?? ''] || item.action}</Button>{!item.allowed && <small className="table-subtext">{actionReason(item.reason)}</small>}</span>)}</Space>
      {action.error && <Alert className="section-card" type="error" title="发布处理未完成" description={<>{action.error.message}{action.error instanceof RequestError && action.error.status === 409 && <p>业务状态已变化，核对最新条件后更新操作依据；处理原因与旧发布选择继续保留。</p>}</>} />}
      <Button className="section-card" onClick={async () => { const current = await detail.reload(); const value = current.data as Contract<'ReleaseDeployment'> | undefined; if (value) setBasis(previous => previous.id === value.id ? { ...previous, version: value.version } : previous); action.reset(); }}>核对状态并更新操作依据</Button></div>
      <details className="section-card"><summary>最近实际节点报告（最多一千条）</summary><pre>{json(reports.data ?? [])}</pre></details>
    </Card>}
    <Drawer title="组合程序、规则和配置" open={compose} onClose={() => setCompose(false)} width="min(1100px, 100vw)" extra={<Space wrap><Button loading={validate.isPending} disabled={!manifest || !mayCreate} onClick={() => validate.mutate()}>校验依赖与兼容</Button><Button type="primary" loading={save.isPending} disabled={!mayCreate || !validation?.value.valid || validation.input !== json(manifest)} onClick={() => save.mutate()}>登记固定发布</Button></Space>}>
      <Button onClick={() => { setManifest({ schema_version: 'smartfactory-release-v1', id: 'release-' + crypto.randomUUID(), name: '新的云边发布', program: 'edge', components: [] }); setValidation(undefined); }}>创建首份发布清单</Button><Form className="section-card" layout="vertical"><Form.Item label="参考已有固定清单"><Select aria-label="参考已有固定清单" showSearch optionFilterProp="label" onChange={id => { const source = releases.data?.find(item => item.id === id)?.manifest; if (source) setManifest({ ...source, template: undefined, id: 'release-' + crypto.randomUUID(), name: source.name + ' · 新发布' }); setValidation(undefined); }} options={(releases.data ?? []).filter(item => !item.manifest?.template?.batch_id).map(item => ({ value: item.id, label: `${item.manifest?.name} / ${item.id}` }))} /></Form.Item>{manifest && <><Form.Item label="固定发布身份" required><Input aria-label="固定发布身份" value={manifest.id} onChange={event => setManifest({ ...manifest, id: event.target.value })} /></Form.Item><Form.Item label="固定发布名称" required><Input aria-label="固定发布名称" value={manifest.name} onChange={event => setManifest({ ...manifest, name: event.target.value })} /></Form.Item><Form.Item label="已登记程序工件"><Select aria-label="已登记程序工件" value={manifest.components?.find(item => item.kind === 'program')?.sha256} onChange={sha => { const artifact = artifacts.data?.find(item => item.sha256 === sha); if (artifact) setManifest(replaceProgram(manifest, artifact)); }} options={(artifacts.data ?? []).filter(item => !manifest.components?.some(component => component.kind === 'program') || item.build?.program === manifest.program).map(item => ({ value: item.sha256, label: `${item.build?.version} / ${item.build?.goos} / ${item.build?.goarch} / 数据库 ${String(item.build?.migration_minimum)} 至 ${String(item.build?.migration_maximum)} / ${item.sha256}` }))} /></Form.Item></>}</Form>
      {manifest && <><ManifestDetails manifest={manifest} digest={validation?.input === json(manifest) ? validation.value.sha256 : undefined} order={validation?.input === json(manifest) ? validation.value.order : undefined} /><Form layout="vertical"><Form.Item label="规则和配置组件"><Select aria-label="规则和配置组件" mode="multiple" value={manifest.components?.filter(item => item.kind !== 'program').map(item => item.id + ':' + item.sha256)} onChange={ids => { const available = availableComponents; const picked = ids.map(id => manifest.components?.find(item => item.id + ':' + item.sha256 === id) ?? available.find(item => item.id + ':' + item.sha256 === id)).filter((item): item is Contract<'ReleaseComponent'> => !!item); const next = { ...manifest, components: [...manifest.components?.filter(item => item.kind === 'program') ?? [], ...picked] }; const program = artifacts.data?.find(item => item.sha256 === next.components.find(item => item.kind === 'program')?.sha256); setManifest(program ? replaceProgram(next, program) : next); }} options={[...new Map(availableComponents.filter(item => item.kind !== 'program').map(item => [item.id + ':' + item.sha256, { value: item.id + ':' + item.sha256, label: `${item.id} / ${item.kind} / v${item.version} / ${item.sha256}` }])).values()]} /></Form.Item></Form></>}
      {(validate.error || save.error) && <Alert type="error" title="固定发布未完成" description={validate.error?.message || save.error?.message} />}
      {validation && <Alert type={validation.value.valid && validation.input === json(manifest) ? 'success' : 'warning'} title={validation.input !== json(manifest) ? '组件已变化，请再次校验' : validation.value.valid ? '依赖与兼容校验通过' : '清单包含待处理项'} description={validation.value.issues?.map(issue => <p key={issue.component_id + ':' + issue.code}>{issue.component_id} / {issue.code}：{issue.message}{issue.recovery?.map((step, index) => <span className="table-subtext" key={index}>{index + 1}. {step}</span>)}</p>)} />}
    </Drawer>
    <Drawer title="新建节点发布批次" open={deployOpen} onClose={() => setDeployOpen(false)} width="min(900px, 100vw)" extra={<Button type="primary" loading={deploy.isPending} disabled={!mayCreate} onClick={() => deploy.mutate()}>开始分批发布</Button>}><Form layout="vertical"><Form.Item label="发布批次身份" required><Input aria-label="发布批次身份" value={request.id} onChange={event => setRequest({ ...request, id: event.target.value, request_id: crypto.randomUUID() })} /></Form.Item><Form.Item label="待发布固定清单" required><Select aria-label="待发布固定清单" value={request.release_id || undefined} showSearch optionFilterProp="label" onChange={value => setRequest({ ...request, release_id: value, batches: [[]], request_id: crypto.randomUUID() })} options={(releases.data ?? []).map(item => ({ value: item.id, label: `${item.manifest?.name} / ${item.id}` }))} /></Form.Item><Form.Item label="发布所属组织" required><Input aria-label="发布所属组织" value={request.group_id} onChange={event => setRequest({ ...request, group_id: event.target.value })} /></Form.Item><Form.Item label="筛选节点、程序或用途"><Input aria-label="筛选发布节点" value={nodeFilter} onChange={event => setNodeFilter(event.target.value)} /></Form.Item>{request.batches?.map((batch, index) => <Form.Item label={'第 ' + (index + 1) + ' 批节点身份'} key={index} required><Space className="release-batch-input"><Select aria-label={'第 ' + (index + 1) + ' 批节点身份'} mode="multiple" value={batch ?? []} showSearch optionFilterProp="label" options={nodeOptions.map(option => ({ ...option, disabled: option.disabled || !!request.batches?.some((other, at) => at !== index && other?.includes(option.value)) }))} onChange={value => setRequest({ ...request, batches: request.batches?.map((other, at) => at === index ? value : other) ?? [] })} /><Button disabled={request.batches?.length === 1} onClick={() => setRequest({ ...request, batches: request.batches?.filter((_, at) => at !== index) ?? [] })}>删除此批</Button></Space></Form.Item>)}<Button disabled={(request.batches?.length ?? 0) >= 20} onClick={() => setRequest({ ...request, batches: [...request.batches ?? [], []] })}>增加后续批次</Button><Form.Item className="section-card" label="分批发布原因" required><Input.TextArea aria-label="分批发布原因" rows={3} value={request.reason} onChange={event => setRequest({ ...request, reason: event.target.value })} /></Form.Item></Form>{chosen?.manifest && <ManifestDetails manifest={chosen.manifest} digest={chosen.sha256} order={chosen.order} />}{deploy.error && <Alert type="error" title="节点批次未开始" description={deploy.error.message} />}</Drawer>
  </>;
}
export function ManifestDetails({ manifest, digest, order }: { manifest?: Contract<'ReleaseManifest'>; digest?: string; order?: string[] | null }) {
  return <div className="release-manifest"><Descriptions column={1} items={[{ key: 'sha', label: '完整发布摘要', children: <code>{digest || '完成校验后取得'}</code> }, { key: 'order', label: '依赖启用次序', children: order?.join(' → ') || '完成校验后取得' }]} /><Table size="small" rowKey="id" dataSource={manifest?.components ?? []} scroll={{ x: 1300 }} pagination={false} expandable={{ expandedRowRender: component => <pre>{json({ build: component.build, content: component.content, reference: component.configuration })}</pre> }} columns={[{ title: '组件身份 / 类型', render: (_, component) => `${component.id} / ${component.kind}` }, { title: '固定版本 / 格式', render: (_, component) => `${component.version} / ${component.format}` }, { title: '内容摘要', dataIndex: 'sha256', render: value => <code className="release-digest">{value}</code> }, { title: '固定配置与凭据引用', render: (_, component) => component.configuration ? `${component.configuration.kind} / ${component.configuration.id} / v${String(component.configuration.version)}` : '程序或规则内容' }, { title: '依赖组件', render: (_, component) => component.depends_on?.map(dependency => `${dependency.id} / v${dependency.version} / ${dependency.sha256}`).join('；') || '无前置依赖' }, { title: '目标节点', render: (_, component) => component.target_node_ids?.join('、') || '所有选中节点' }, { title: '所需能力', render: (_, component) => component.required_capabilities?.join('、') || '按程序与身份核验' }]} /></div>;
}
