import { lazy, Suspense, useEffect, useState } from 'react';
import { Alert, App, Button, ConfigProvider, Form, Input, Select, Space, Spin, Tag } from 'antd';
import { api, post, session } from './api';
import { bindQueryIdentity, clearQueryIdentity } from './query-cache';
import type { User } from './types';
import { Assets, Audit, Configuration, DataPage, Overview, Organization, Runtime } from './views';
import { Screen } from './screen';
const Definitions = lazy(() => import('./definitions').then(module => ({default:module.Definitions})));
const AlarmWorkbench = lazy(() => import('./alarm-workbench').then(module => ({default:module.AlarmWorkbench})));
const WorkOrders = lazy(() => import('./work-orders').then(module => ({default:module.WorkOrders})));
const SceneTemplates = lazy(() => import('./scene-templates').then(module => ({default:module.SceneTemplates})));
const ProtocolConfigurations = lazy(() => import('./protocol-configurations').then(module => ({default:module.ProtocolConfigurations})));
const Assistant = lazy(() => import('./assistant').then(module => ({default:module.Assistant})));
const Releases = lazy(() => import('./releases').then(module => ({default:module.Releases})));
const WorkloadIdentities = lazy(() => import('./workload-identities').then(module => ({default:module.WorkloadIdentities})));
import { Jobs, Notifications, Plugins } from './workflows';
import { BackgroundTasks } from './tasks';
import { Executions } from './executions';
import { HistoryAnalysis } from './history';

export type Surface = 'cloud' | 'edge' | 'screen';
const names: Record<string, string> = { overview: '运行概览', assets: '设备与资产', data: '数据监控', analysis: '数据分析', alarm: '告警编排', strategy: '联动预案', executions: '审批与执行', organization: '组织与权限', configuration: '配置中心', audit: '业务审计', runtime: '运行状态', assistant: 'AI 助手', jobs: '历史补算', tasks: '后台任务', history: '历史分析', notifications: '通知记录', plugins: '同步插件', 'alarm-workbench': '告警处置', 'work-orders': '工单与交接', 'scene-templates': '场景模板', 'protocol-configurations': '协议与设备参数', releases: '云边发布', 'workload-identities': '节点身份与配置' };
export function Application() {
  const surface = (document.documentElement.dataset.surface ?? 'cloud') as Surface; const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false); const [page, setPage] = useState(location.hash.slice(1) || 'overview'); const [node, setNode] = useState(''); const [serverMode, setServerMode] = useState(''); const [refreshMS, setRefreshMS] = useState(Number(localStorage.getItem('sf.refresh-ms') || 1000));
  const { message } = App.useApp();
  useEffect(() => { if (!session.get()) { setReady(true); return; } api<{ user: User; node_id: string; mode: string; refresh_ms: number }>('/me').then(r => { bindQueryIdentity(r.user); setUser(r.user); setNode(r.node_id); setServerMode(r.mode); if (!localStorage.getItem('sf.refresh-ms')) setRefreshMS(r.refresh_ms || 1000); }).catch(() => session.clear()).finally(() => setReady(true)); }, []);
  useEffect(() => {
    const expired = () => { session.clear(); clearQueryIdentity(); setUser(null); };
    const authorizationChanged = async () => {
      const previousToken = session.get();
      if (!previousToken) return;
      try {
        const current = await api<{ user: User; node_id: string; mode: string }>('/me');
        if (session.get() === previousToken) { bindQueryIdentity(current.user); setUser(current.user); setNode(current.node_id); setServerMode(current.mode); }
      } catch (error) { /* Authentication expiry is handled by the shared event. */ }
    };
    const hash = () => setPage(location.hash.slice(1) || 'overview');
    window.addEventListener('sf-auth-expired', expired); window.addEventListener('sf-authz-changed', authorizationChanged); window.addEventListener('hashchange', hash);
    return () => { window.removeEventListener('sf-auth-expired', expired); window.removeEventListener('sf-authz-changed', authorizationChanged); window.removeEventListener('hashchange', hash); };
  }, []);
  const logout = async () => { try { await post('/logout'); } finally { session.clear(); clearQueryIdentity(); setUser(null); } };
  if (!ready) return <div className="center-stage"><Spin tip="正在读取会话" /></div>;
  if (!user) return <Login surface={surface} onLogin={async user => { bindQueryIdentity(user); setUser(user); const r = await api<{ node_id: string; mode: string; refresh_ms: number }>('/me'); setNode(r.node_id); setServerMode(r.mode); if (!localStorage.getItem('sf.refresh-ms')) setRefreshMS(r.refresh_ms || 1000); }} />;
  if (surface === 'screen') return <Screen key={JSON.stringify([user.id,user.version,user.roles,user.resources])} user={user} refreshMS={refreshMS} mode={serverMode} onLogout={logout} />;
  const admin = user.roles.includes('admin'); const engineer = admin || user.roles.includes('engineer');
  const pages = surface === 'edge' ? ['overview', 'assets', 'protocol-configurations', 'data', 'alarm-workbench', 'work-orders', 'scene-templates', 'releases', 'workload-identities', 'executions', 'notifications', 'jobs', 'tasks', 'history', 'runtime'] : ['overview', 'assets', 'protocol-configurations', 'data', 'alarm-workbench', 'work-orders', 'scene-templates', 'releases', 'workload-identities', ...(engineer || user.ai ? ['analysis', 'alarm', 'strategy'] : []), 'executions', 'notifications', 'jobs', 'tasks', 'history', ...(admin ? ['organization', 'configuration', 'plugins', 'audit'] : []), 'runtime', 'assistant'];
  const changeRefresh = (value: number) => { setRefreshMS(value); localStorage.setItem('sf.refresh-ms', String(value)); void message.success(value === -1 ? '已启用数据实时推送' : value ? `刷新周期已设为 ${value / 1000} 秒` : '已切换为手动查询'); };
  const activePage = page.split('?')[0];
  const routeParameters = new URLSearchParams(page.split('?')[1] ?? '');
  const initialTask = routeParameters.get('task') ?? '';
  const content = activePage === 'assets' ? <Assets user={user} mode={serverMode} initialID={routeParameters.get('device') ?? ''} /> : activePage === 'data' ? <DataPage refreshMS={refreshMS} initialDevice={routeParameters.get('device') ?? ''} /> : activePage === 'analysis' || activePage === 'alarm' || activePage === 'strategy' ? <Definitions kind={activePage} user={user} initialDefinition={routeParameters.get('definition') ?? ''} initialDraft={routeParameters.get('draft') ?? ''} /> : activePage === 'alarm-workbench' ? <AlarmWorkbench refreshMS={refreshMS} initialID={routeParameters.get('alarm') ?? ''} /> : activePage === 'work-orders' ? <WorkOrders user={user} refreshMS={refreshMS} initialID={routeParameters.get('work_order') ?? ''} /> : activePage === 'scene-templates' ? <SceneTemplates user={user} mode={serverMode} /> : activePage === 'releases' ? <Releases user={user} mode={serverMode} refreshMS={refreshMS} initialID={routeParameters.get('deployment') ?? ''} initialRelease={routeParameters.get('release') ?? ''} /> : activePage === 'workload-identities' ? <WorkloadIdentities user={user} mode={serverMode} refreshMS={refreshMS} nodeID={node} /> : activePage === 'protocol-configurations' ? <ProtocolConfigurations mode={serverMode} initialID={routeParameters.get('device') ?? ''} /> : activePage === 'executions' ? <Executions user={user} refreshMS={refreshMS} local={serverMode === 'edge'} initialID={routeParameters.get('execution') ?? ''} /> : activePage === 'jobs' ? <Jobs user={user} refreshMS={refreshMS} /> : activePage === 'tasks' ? <BackgroundTasks refreshMS={refreshMS} initialID={initialTask} /> : activePage === 'history' ? <HistoryAnalysis user={user} refreshMS={refreshMS} initialRun={routeParameters.get('run') ?? ''} initialCandidate={routeParameters.get('candidate') ?? ''} /> : activePage === 'notifications' ? <Notifications user={user} refreshMS={refreshMS} /> : activePage === 'plugins' ? <Plugins /> : activePage === 'organization' ? <Organization /> : activePage === 'configuration' ? <Configuration /> : activePage === 'audit' ? <Audit /> : activePage === 'runtime' ? <Runtime refreshMS={refreshMS} /> : activePage === 'assistant' ? <Assistant user={user} initialID={routeParameters.get('investigation') ?? ''} /> : <Overview surface={surface} refreshMS={refreshMS} />;
  return <div className={'workspace surface-' + surface}><aside className="sidebar"><a className="brand" href="#overview"><span className="brand-monogram">SF</span><span>SmartFactory<small>{surface === 'edge' ? '现场工作台' : '生产安全控制台'}</small></span></a><div className="workspace-caption">示例工厂 / {node || '连接中'}</div><nav aria-label="主导航">{pages.map(key => <button key={key} className={activePage === key ? 'nav-item selected' : 'nav-item'} onClick={() => { location.hash = key; }}><span className="nav-marker" />{names[key]}</button>)}</nav><div className="sidebar-footer"><span className="connection-indicator" />独立实例 · {serverMode === 'edge' ? '边缘运行' : '云端运行'}<small>规则版本与操作记录全程保存</small></div></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb">{surface === 'edge' ? '现场工作台' : '云端控制台'}<span>/</span><strong>{names[activePage] || '运行概览'}</strong></div><Space size={14}><Select aria-label="页面刷新方式" size="small" value={refreshMS} onChange={changeRefresh} options={[{ value: -1, label: '实时推送' }, { value: 1000, label: '每秒刷新' }, { value: 5000, label: '每 5 秒刷新' }, { value: 0, label: '手动查询' }]} /><span className="user-name">{user.name}</span><Button size="small" onClick={() => void logout()}>退出</Button></Space></header><main className="page-content">{surface === 'edge' && serverMode !== 'edge' && <Alert type="warning" showIcon title="此地址连接到云端服务" description="现场操作请使用边缘节点提供的工作台地址，本页显示当前服务的数据。" />}<Suspense key={JSON.stringify([user.id,user.version,user.roles,user.resources])} fallback={<Spin tip="正在读取页面" />}>{content}</Suspense></main><footer className="page-footer">SmartFactory · {node}<span>界面时间使用 Asia/Shanghai 时区</span></footer></div></div>;
}
function Login({ surface, onLogin }: { surface: Surface; onLogin: (u: User) => Promise<void> }) { const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const submit = async (values: { login: string; password: string; code?: string }) => { setLoading(true); setError(''); try { const r = await post<{ token: string; user: User }>('/login', values); session.set(r.token); await onLogin(r.user); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }; return <div className="login-page"><div className="login-story"><div className="brand"><span className="brand-monogram">SF</span><span>SmartFactory</span></div><div className="login-copy"><span className="eyebrow">工业现场 · 数据与控制</span><h1>看见现场变化，<br />让每次执行都有依据。</h1><p>从设备观测到分析判断，再到现场确认与结果反馈，连接工厂的日常运行。</p><div className="login-network"><span>设备采集</span><i /><span>边缘自治</span><i /><span>云端协作</span></div></div><small>ThingsBoard CE / Edge · SmartFactory</small></div><div className="login-form"><Tag color="cyan">{surface === 'edge' ? '边缘现场' : surface === 'screen' ? '运行大屏' : '云端控制台'}</Tag><h2>登录工作空间</h2><p>使用已分配的账号访问设备、规则与执行记录。</p>{error && <Alert title="登录未完成" description={error} type="error" showIcon />}<Form layout="vertical" onFinish={submit} requiredMark={false}><Form.Item label="账号" name="login" rules={[{ required: true, message: '请输入账号' }]}><Input size="large" autoComplete="username" /></Form.Item><Form.Item label="密码" name="password" rules={[{ required: true, message: '请输入密码' }]}><Input.Password size="large" autoComplete="current-password" /></Form.Item>{surface === 'edge' && <Form.Item label="现场二次认证码（执行安全确认时填写）" name="code"><Input inputMode="numeric" maxLength={6} autoComplete="one-time-code" /></Form.Item>}<Button type="primary" htmlType="submit" size="large" loading={loading} block>登录</Button></Form><div className="login-note">账号权限由所属组织和平台授权共同管理；现场页面保留最近同步的离线授权。</div></div></div>; }
