export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export interface Dashboard { id: string; title: string; group_id: string; version: number; device_ids: string[]; keys: string[]; metrics: { device_id: string; key: string; label: string }[]; window_ms: number; refresh_ms: number; show_sources: boolean; show_alarms: boolean }
export interface User { id: string; name: string; login: string; roles: string[]; resources: string[]; department_id: string; active: boolean; ai: boolean; teams: string[]; version: number }
export interface Entity { id: string; name: string; kind: 'asset' | 'device' | 'edge'; parent_id?: string; edge_id?: string; protocol?: string; status: string; version: number; sampling_ms?: number; tags?: Record<string, string>; config?: Json }
export interface Point { id: string; device_id: string; key: string; value: Json; quality: string; quality_reason?: string; observed_ms: number; received_ms: number; source_id: string; unit?: string; revision: number; time_source: string; late: boolean }
export interface Source { id: string; last_seen_ms: number; status: string; backfill: string; reason?: string }
export interface Revision { id: string; device_id: string; key: string; at_ms: number; before: Json; after: Json; reason: string; version: number }
export interface DataResult { points: Point[]; latest?: Point[]; quality: { good: number; bad: number; uncertain: number; excluded: number; missing: number | null; completeness: string }; sources: Source[]; revisions: Revision[]; gaps?: { id: string; device_id: string; key: string; from_ms: number; to_ms: number; missing: number; scope: string; reason: string }[]; data_version: number; truncated: boolean }
export interface RuleNode { id: string; type: string; label?: string; params: Record<string, Json>; position?: { x: number; y: number }; inputs?: { name: string; type: string }[]; outputs?: { name: string; type: string }[] }
export interface Definition { id: string; name: string; kind: 'analysis' | 'alarm' | 'strategy'; schema_version: string; version: number; status: string; group_id: string; effective_ms: number; nodes: RuleNode[]; connections: { from: string; from_port: string; to: string; to_port: string }[]; outputs: { key: string; type: string; unit?: string; node_id: string }[]; dependencies: string[]; selector: { device_ids: string[]; keys: string[]; asset_id?: string; window_ms?: number }; policy: Record<string, Json> }
export interface Draft { id: string; definition: Definition; base_version: number; version: number; author_id: string; updated_ms: number }
export interface Execution { downlink_id: string; definition_id: string; definition_version: number; status: string; risk_category: string; risk_level: number; override: boolean; reason?: string; version: number; created_ms: number; approval_expires_ms: number; approvals: { user_id: string; role: string; at_ms: number; local: boolean; step_up: boolean }[]; steps: { step_id: string; command_id: string; status: string; message: string }[]; snapshot: Point[] }
export interface Alarm { id: string; definition_id: string; entity_id: string; severity: string; active: boolean; acknowledged: boolean; started_ms: number; updated_ms: number; count: number; historical: boolean; value: Json; version: number }
export interface Parameter { id: string; program: string; category: string; description: string; schema: Record<string, Json>; value: Json; dynamic: boolean; secret: boolean; version: number; effective: Record<string, number>; state: string; applications?: Record<string, { version: number; state: string; reason?: string; at_ms: number }> }
