import { useEffect, useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Alert, Button, Card, Descriptions, Drawer, Form, Input, Select, Space, Switch, Table, Tag } from 'antd';
import { json, RequestError, timestamp, useResource } from './api';
import { callOperation, type Contract } from './generated-client';
import { useRetainedEdit } from './editor-state';
import { ErrorNotice, PageTitle } from './views';
import type { User } from './types';
import { releaseStates } from './release-state';

type EditableIdentity = Omit<Contract<'WorkloadIdentity'>, 'generation' | 'version' | 'updated_ms' | 'instance_id' | 'instance_epoch'>;
type Edit = { identity: EditableIdentity; version: Contract<'WorkloadIdentity'>['version'] };
const editable = (identity: Contract<'WorkloadIdentity'>): EditableIdentity => ({ id: identity.id, node_id: identity.node_id, program: identity.program, purpose: identity.purpose, enabled: identity.enabled, capabilities: identity.capabilities ?? [], parameter_ids: identity.parameter_ids ?? [], connector_ids: identity.connector_ids ?? [] });
export function WorkloadIdentities({ user, mode, refreshMS, nodeID = '' }: { user: User; mode: string; refreshMS: number; nodeID?: string }) {
  const interval = refreshMS === 0 ? 0 : Math.min(refreshMS > 0 ? refreshMS : 1000, 5000);
  const data = useResource<Contract<'WorkloadIdentity'>[]>('/workload-identities', interval);
  const reports = useResource<Contract<'ConfigurationReport'>[]>('/configuration-reports', interval);
  const runtime = useResource<Contract<'RuntimeConfiguration'>[]>(user.roles.includes('admin') || user.resources.includes('*') || user.resources.includes(nodeID) ? '/configuration-runtime' : null, interval);
  const parameters = useResource<Contract<'Parameter'>[]>(user.roles.includes('admin') ? '/config' : null);
  const [editing, setEditing] = useRetainedEdit<Edit | null>('workload-edit', null);
  const [open, setOpen] = useState(false);
  const [filter, setFilter] = useState('');
  const [rotation, setRotation] = useState<Contract<'WorkloadIdentity'>>();
  const [credential, setCredential] = useState('');
  const mayEdit = mode === 'cloud' && user.roles.includes('admin');
  useEffect(() => { const clear = () => { setCredential(''); setRotation(undefined); setOpen(false); }; window.addEventListener('sf-cache-cleared', clear); return () => window.removeEventListener('sf-cache-cleared', clear); }, []);
  const reload = async () => { await Promise.all([data.reload(), reports.reload(), runtime.reload()]); };
  const save = useMutation({ mutationFn: async () => {
    if (!editing) throw new Error('请选择工作负载身份');
    const identity = editing.identity;
    if (![identity.id, identity.node_id, identity.program, identity.purpose].every(value => value.trim())) throw new Error('请填写身份、节点、程序和用途');
    // The shared response schema requires read-only fields. Their zero values
    // satisfy the generated type; the authority assigns their actual values.
    const saved = await callOperation('post_workload_identities', { body: { identity: { ...identity, generation: 0, version: 0, instance_epoch: 0, updated_ms: 0 }, expected_version: editing.version } }, { exact: true });
    setEditing({ identity: editable(saved), version: saved.version }); setOpen(false); await reload(); return saved;
  } });
  const rotate = useMutation({ mutationFn: async () => {
    if (!rotation || credential.length < 32 || credential.length > 512) throw new Error('新凭据需要包含三十二至五百一十二个字符');
    const input = credential; setCredential('');
    const saved = await callOperation('post_workload_identities_id_rotate', { parameters: { path: { id: rotation.id } }, body: { credential: input, expected_version: rotation.version } }, { exact: true });
    setRotation(undefined); await reload(); return saved;
  } });
  const values = (data.data ?? []).filter(identity => !filter || [identity.id, identity.node_id, identity.program, identity.purpose].some(value => value.includes(filter)));
  const secret = (id?: string) => parameters.data?.some(parameter => parameter.id === id && parameter.secret);
  return <><PageTitle title="节点身份与配置报告" note="按节点、程序、用途和对象范围管理工作负载，核对配置消费者实际运行结果。" actions={<Space wrap><Button onClick={() => void reload()}>更新身份与报告</Button><Button disabled={!mayEdit} type="primary" onClick={() => { setEditing({ version: 0, identity: { id: '', node_id: '', program: 'edge', purpose: 'runtime', enabled: true, capabilities: ['config.v2', 'config.read', 'config.report'], parameter_ids: [], connector_ids: [] } }); setOpen(true); save.reset(); }}>登记工作负载身份</Button></Space>} />
    <ErrorNotice error={data.error || reports.error || runtime.error} retry={() => void reload()} /><Input className="section-card" aria-label="筛选节点身份" placeholder="按节点、程序、用途或身份筛选" value={filter} onChange={event => setFilter(event.target.value)} />
    <Card className="section-card" title="工作负载身份"><Table rowKey="id" dataSource={values} scroll={{ x: 1150 }} expandable={{ expandedRowRender: identity => <Descriptions column={{ xs: 1, md: 2 }} items={[{ key: 'capabilities', label: '能力', children: identity.capabilities?.join('、') || '未授权能力' }, { key: 'parameters', label: '参数及凭据引用范围', children: identity.parameter_ids?.join('、') || '未授权参数' }, { key: 'connectors', label: '所属连接器范围', children: identity.connector_ids?.join('、') || '未授权连接器' }, { key: 'instance', label: '当前实例 / 代次', children: `${identity.instance_id || '尚未认证'} / ${String(identity.instance_epoch)}` }]} /> }} columns={[{ title: '工作负载身份', dataIndex: 'id' }, { title: '节点', dataIndex: 'node_id' }, { title: '程序 / 用途', render: (_, identity) => `${identity.program} / ${identity.purpose}` }, { title: '当前授权', render: (_, identity) => <Tag color={identity.enabled ? 'success' : 'error'}>{identity.enabled ? '已启用' : '已停用'}</Tag> }, { title: '凭据代次', render: (_, identity) => String(identity.generation) }, { title: '业务版本', render: (_, identity) => String(identity.version) }, { title: '最近变更', dataIndex: 'updated_ms', render: value => timestamp(Number(value)) }, { title: '身份与凭据', render: (_, identity) => <Space wrap><Button disabled={!mayEdit} onClick={() => { setEditing({ identity: editable(identity), version: identity.version }); setOpen(true); save.reset(); }}>编辑范围或停用</Button><Button disabled={!mayEdit} onClick={() => { setRotation(identity); setCredential(''); rotate.reset(); }}>轮换私有凭据</Button></Space> }]} /></Card>
    <Card title="配置准备、应用与实际运行" className="section-card"><Table rowKey={report => [report.identity_id, report.instance_id, report.kind, report.id].join(':')} dataSource={(reports.data ?? []).filter(report => !filter || [report.node_id, report.identity_id, report.program, report.purpose].some(value => value.includes(filter)))} scroll={{ x: 1350 }} expandable={{ expandedRowRender: report => <Descriptions column={1} items={[{ key: 'instance', label: '认证实例 / 代次 / 凭据代次', children: `${report.instance_id} / ${String(report.instance_epoch)} / ${String(report.generation)}` }, { key: 'sequence', label: '实际报告序号', children: String(report.sequence) }, { key: 'value', label: '实际消费者值', children: secret(report.id) ? '凭据值已隐藏；页面显示引用及版本' : report.effective_value === undefined ? '此报告未包含公开消费者值' : <pre>{json(report.effective_value)}</pre> }, ...(['desired', 'prepared', 'applied', 'running'] as const).map((field, index) => ({ key: field, label: ['期望版本与摘要', '准备版本与摘要', '应用版本与摘要', '运行版本与摘要'][index], children: `${String(report[field]?.version)} / ${report[field]?.digest || '尚未确认'}` }))]} /> }} columns={[{ title: '节点 / 程序 / 用途', render: (_, report) => <>{report.node_id}<small className="table-subtext">{report.program} / {report.purpose} / {report.identity_id}</small></> }, { title: '配置引用', render: (_, report) => `${report.kind} / ${report.id}` }, ...(['desired', 'prepared', 'applied', 'running'] as const).map((field, index) => ({ title: ['期望版本', '准备版本', '应用版本', '实际运行版本'][index], render: (_: unknown, report: Contract<'ConfigurationReport'>) => String(report[field]?.version ?? 0) })), { title: '处理状态', render: (_, report) => <Tag color={report.state === 'failed' ? 'error' : report.state === 'running' ? 'success' : 'warning'}>{releaseStates[report.state] || report.state}</Tag> }, { title: '处理事项', dataIndex: 'reason' }, { title: '实际报告时间', dataIndex: 'at_ms', render: value => timestamp(Number(value)) }]} /></Card>
    <Card title="当前服务的实际配置消费者" className="section-card"><Table rowKey={item => item.reference?.kind + ':' + item.reference?.id} dataSource={runtime.data ?? []} scroll={{ x: 850 }} columns={[{ title: '配置引用', render: (_, item) => `${item.reference?.kind} / ${item.reference?.id}` }, { title: '固定来源版本', render: (_, item) => String(item.reference?.version) }, { title: '消费者应用代次', render: (_, item) => String(item.apply_generation ?? 0) }, { title: '实际消费者摘要', dataIndex: 'consumer_digest', render: value => <code className="release-digest">{value}</code> }, { title: '公开生效值', render: (_, item) => secret(item.reference?.id) ? '凭据值已隐藏' : <pre>{json(item.effective_value)}</pre> }]} /></Card>
    <Drawer title="编辑工作负载身份" open={open} onClose={() => setOpen(false)} width="min(780px, 100vw)" extra={<Button type="primary" disabled={!mayEdit} loading={save.isPending} onClick={() => save.mutate()}>保存身份范围</Button>}>
      {editing && <><p>已阅业务版本 {String(editing.version)}。保存停用、范围变化或凭据轮换后，原实例与旧订阅按当前身份重新核验。</p><Form layout="vertical">{(['id', 'node_id', 'program', 'purpose'] as const).map((key, index) => <Form.Item key={key} label={['工作负载标识', '归属节点', '所属程序', '使用用途'][index]} required><Input aria-label={['工作负载标识', '归属节点', '所属程序', '使用用途'][index]} disabled={key === 'id' && !!editing.version} value={editing.identity[key]} onChange={event => setEditing({ ...editing, identity: { ...editing.identity, [key]: event.target.value } })} /></Form.Item>)}<Form.Item label="启用身份"><Switch aria-label="启用身份" checked={editing.identity.enabled} onChange={enabled => setEditing({ ...editing, identity: { ...editing.identity, enabled } })} /></Form.Item>{(['capabilities', 'parameter_ids', 'connector_ids'] as const).map((key, index) => <Form.Item key={key} label={['允许的能力', '参数及凭据引用范围', '连接器固定引用范围'][index]}><Select aria-label={['允许的能力', '参数及凭据引用范围', '连接器固定引用范围'][index]} mode="tags" tokenSeparators={[',', '，']} value={editing.identity[key] ?? []} onChange={value => setEditing({ ...editing, identity: { ...editing.identity, [key]: value } })} options={(key === 'capabilities' ? ['release', 'config.v2', 'config.read', 'config.report', 'credential.resolve', 'goos:linux', 'goarch:amd64', 'goos:darwin', 'goarch:arm64', 'connector:mqtt_device', 'connector:modbus_tcp', 'connector:opcua'] : [...new Set((data.data ?? []).flatMap(identity => identity[key] ?? []))]).map(value => ({ value, label: value }))} /></Form.Item>)}</Form></>}
      {save.error && <Alert type="error" title="身份范围未保存" description={save.error.message} />}{save.error instanceof RequestError && save.error.status === 409 && <Button onClick={async () => { const current = await data.reload(); const identity = (current.data as Contract<'WorkloadIdentity'>[] | undefined)?.find(item => item.id === editing?.identity.id); if (identity && editing) setEditing(previous => previous?.identity.id === identity.id ? { ...previous, version: identity.version } : previous); save.reset(); }}>保留编辑并更新已阅版本</Button>}
    </Drawer>
    <Drawer title="轮换工作负载私有凭据" open={!!rotation} onClose={() => { setRotation(undefined); setCredential(''); }} width="min(650px, 100vw)" extra={<Button disabled={!mayEdit || credential.length < 32 || credential.length > 512} loading={rotate.isPending} onClick={() => rotate.mutate()}>确认轮换凭据</Button>}><p>{rotation?.id} / 已阅版本 {String(rotation?.version ?? 0)}。将同一新凭据写入对应节点的私有部署文件，再由节点按新代次认证。</p><Form layout="vertical"><Form.Item label="新的私有工作负载凭据" required><Input.Password aria-label="新的私有工作负载凭据" visibilityToggle={false} autoComplete="new-password" value={credential} onChange={event => setCredential(event.target.value)} /></Form.Item></Form>{rotate.error && <Alert type="error" title="凭据轮换未完成" description={rotate.error.message} />}{rotate.error instanceof RequestError && rotate.error.status === 409 && <Button onClick={async () => { const current = await data.reload(); setRotation((current.data as Contract<'WorkloadIdentity'>[] | undefined)?.find(item => item.id === rotation?.id)); rotate.reset(); }}>更新身份版本后重新填写凭据</Button>}</Drawer>
  </>;
}
