import { useEffect, useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Alert, Button, Card, Checkbox, Descriptions, Drawer, Form, Input, Modal, Select, Space, Table } from 'antd';
import { json, useResource } from './api';
import { callOperation, type Contract } from './generated-client';
import type { User } from './types';
import { exactTimestamp } from './precision';
import { PageTitle, ErrorNotice } from './views';
import { resourceLink } from './resource-navigation';

const labels: Record<string,string> = { assign: '分配责任人', start: '开始处理', update: '修改内容', note: '添加工单备注', complete: '完成工单', reopen: '再次处理', handover: '办理交接' };
export function WorkOrders({ user, refreshMS, initialID = '' }: { user: User; refreshMS: number; initialID?: string }) {
  const orders = useResource<Contract<'WorkOrder'>[]>('/work-orders', refreshMS); const [selected, setSelected] = useState(initialID);
  const detail = useResource<Contract<'WorkOrderDetail'>>(selected ? '/work-orders/' + encodeURIComponent(selected) : null, refreshMS);
  const [creating, setCreating] = useState(false); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [owner, setOwner] = useState(user.id); const [alarms, setAlarms] = useState(''); const [executions, setExecutions] = useState('');
  const [review, setReview] = useState<{ detail: Contract<'WorkOrderDetail'>; action: string; request: string }>(); const [reason, setReason] = useState(''); const [to, setTo] = useState(''); const [pending, setPending] = useState(''); const [evidence, setEvidence] = useState<Contract<'HandoverEvidence'>[]>([]); const [evidenceChoices, setEvidenceChoices] = useState<Contract<'HandoverEvidence'>[]>([]);
  useEffect(() => { if (initialID) setSelected(initialID); }, [initialID]);
  const create = useMutation({ mutationFn: async () => { const saved = await callOperation('post_work_orders', { body: { id: 'work-' + crypto.randomUUID(), request_id: crypto.randomUUID(), title, description, group_id: 'factory', assignee_id: owner, alarm_ids: alarms.split(',').map(value => value.trim()).filter(Boolean), execution_ids: executions.split(',').map(value => value.trim()).filter(Boolean), reason: '创建现场处理工单' } }, { exact: true }); setCreating(false); setSelected(saved.work_order?.id ?? ''); await orders.reload(); return saved; } });
  const openAction = async (action: string) => {
    if (!detail.data?.work_order) return;
    const current = structuredClone(detail.data); setReview({ detail: current, action, request: crypto.randomUUID() }); setReason(''); setTo(''); setPending(''); setEvidence([]); setEvidenceChoices([]);
    if (action === 'handover') {
      const choices: Contract<'HandoverEvidence'>[] = [{ kind: 'work_order', id: current.work_order!.id ?? '', version: current.work_order!.version ?? 0, description: '已阅当前工单' }];
      for (const id of current.work_order!.alarm_ids ?? []) { const alarm = await callOperation('get_alarms_id', { parameters: { path: { id } } }, { exact: true }); choices.push({ kind: 'alarm', id, version: alarm.alarm?.version ?? 0, action_version: alarm.action_version, description: '已阅告警与人工处置' }); }
      for (const id of current.work_order!.execution_ids ?? []) { const execution = await callOperation('get_executions_id', { parameters: { path: { id } } }, { exact: true }); choices.push({ kind: 'execution', id, version: execution.execution?.version ?? 0, description: '已阅执行过程与证据' }); }
      setEvidenceChoices(choices);
    }
  };
  const action = useMutation({ mutationFn: async () => {
    if (!review?.detail.work_order || !reason.trim()) throw new Error('请填写本次处理或交接理由');
    const order = review.detail.work_order; const id = order.id ?? '';
    const saved = review.action === 'handover'
      ? await callOperation('post_work_orders_id_handovers', { parameters: { path: { id } }, body: { request_id: review.request, expected_version: order.version ?? 0, from_user_id: order.assignee_id ?? '', to_user_id: to, pending_items: pending.split('\n').map(item => item.trim()).filter(Boolean), evidence, reason } }, { exact: true })
      : await callOperation('post_work_orders_id_actions', { parameters: { path: { id } }, body: { request_id: review.request, expected_version: order.version ?? 0, action: review.action as Contract<'WorkOrderActionInput'>['action'], reason, assignee_id: to, ...(review.action === 'update' ? { title, description } : {}) } }, { exact: true });
    setReview(undefined); await orders.reload(); await detail.reload(); return saved;
  }, onError: () => { void detail.reload(); } });
  return <><PageTitle title="工单与交接" note="保存现场处理责任、关联依据和未完成事项，按照已阅版本办理处理与交接。" actions={<Button type="primary" onClick={() => { setCreating(true); setTitle(''); setDescription(''); create.reset(); }}>创建工单</Button>} /><ErrorNotice error={orders.error || detail.error} retry={() => { void orders.reload(); void detail.reload(); }} />
    <Card><Table rowKey="id" dataSource={orders.data ?? []} loading={orders.loading} scroll={{ x: 850 }} columns={[{ title: '工单', dataIndex: 'title' }, { title: '状态', dataIndex: 'status' }, { title: '责任人 / 部门', render: (_, order) => `${order.assignee_id} / ${order.assignee_department_id}` }, { title: '版本', render: (_, order) => String(order.version) }, { title: '更新时间', dataIndex: 'updated_ms', render: exactTimestamp }, { title: '操作', render: (_, order) => <Button onClick={() => setSelected(order.id ?? '')}>工单详情</Button> }]} /></Card>
    <Drawer title="工单责任与交接记录" open={!!selected} onClose={() => setSelected('')} width="min(1000px,100vw)">{detail.data?.work_order && <><Descriptions column={2} items={[{ key: 'title', label: '标题', children: detail.data.work_order.title }, { key: 'id', label: '身份与版本', children: `${detail.data.work_order.id} / ${String(detail.data.work_order.version)}` }, { key: 'status', label: '状态', children: detail.data.work_order.status }, { key: 'owner', label: '责任人', children: detail.data.work_order.assignee_id }, { key: 'desc', label: '处理内容', children: detail.data.work_order.description }, { key: 'alarms', label: '关联告警', children: detail.data.work_order.alarm_ids?.map(id => <a key={id} href={resourceLink('alarm',id)}>{id}</a>) }, { key: 'executions', label: '关联执行', children: detail.data.work_order.execution_ids?.map(id => <a key={id} href={resourceLink('execution',id)}>{id}</a>) }]} />{detail.data.responsibility_issue && <Alert type="warning" title="责任人当前条件发生变化" description={detail.data.responsibility_issue} />}
    <Space wrap className="section-actions">{detail.data.allowed_actions?.map(item => <Button key={item.action} disabled={!item.allowed} title={item.reason} onClick={() => { setTitle(detail.data!.work_order!.title ?? ''); setDescription(detail.data!.work_order!.description ?? ''); action.reset(); void openAction(item.action ?? '').catch(error => { setReason(String(error)); }); }}>{labels[item.action ?? ''] || item.action}</Button>)}</Space>
    <h3>处理记录</h3><Table rowKey="id" size="small" dataSource={detail.data.work_order.entries ?? []} columns={[{ title: '动作', dataIndex: 'action' }, { title: '理由', dataIndex: 'reason' }, { title: '人员', render: (_, entry) => entry.actor?.user_id }, { title: '时间', dataIndex: 'at_ms', render: exactTimestamp }]} />
    <h3>交接记录</h3>{detail.data.handovers?.map(item => <Card key={item.id} className="section-card" title={`${item.from_user_id} → ${item.to_user_id}`}><p>{item.reason}，{exactTimestamp(item.at_ms)}</p><p>未完成事项：{item.pending_items?.join('；')}</p><pre>{json(item.evidence)}</pre></Card>)}</>}</Drawer>
    <Modal title="创建处理工单" open={creating} onCancel={() => setCreating(false)} onOk={() => create.mutate()} confirmLoading={create.isPending} okText="保存工单">{create.error && <Alert type="error" title="创建未完成" description={create.error.message} />}<Form layout="vertical"><Form.Item label="工单标题" required><Input aria-label="工单标题" value={title} onChange={event => setTitle(event.target.value)} /></Form.Item><Form.Item label="处理内容"><Input.TextArea aria-label="处理内容" value={description} onChange={event => setDescription(event.target.value)} /></Form.Item><Form.Item label="工单责任人" required><Input aria-label="工单责任人" value={owner} onChange={event => setOwner(event.target.value)} /></Form.Item><Form.Item label="关联告警身份（逗号分隔）"><Input aria-label="关联告警身份" value={alarms} onChange={event => setAlarms(event.target.value)} /></Form.Item><Form.Item label="关联执行身份（逗号分隔）"><Input aria-label="关联执行身份" value={executions} onChange={event => setExecutions(event.target.value)} /></Form.Item></Form></Modal>
    <Modal title={labels[review?.action ?? ''] || '工单变更'} open={!!review} onCancel={() => setReview(undefined)} onOk={() => action.mutate()} confirmLoading={action.isPending} okText="提交工单变更"><p>本次使用已阅工单版本 {String(review?.detail.work_order?.version)}。</p>{action.error && <Alert type="error" title="工单变更未完成" description={action.error.message} />}{action.error && <Button onClick={() => { if (review && detail.data) { setReview({ ...review, detail: structuredClone(detail.data), request: crypto.randomUUID() }); action.reset(); } }}>采用更新后的工单依据</Button>}<Form layout="vertical">{['assign','handover'].includes(review?.action ?? '') && <Form.Item label={review?.action === 'handover' ? '承接人身份' : '新的责任人身份'} required><Input aria-label="新的责任人身份" value={to} onChange={event => setTo(event.target.value)} /></Form.Item>}{review?.action === 'update' && <><Form.Item label="工单标题"><Input aria-label="修改工单标题" value={title} onChange={event => setTitle(event.target.value)} /></Form.Item><Form.Item label="处理内容"><Input.TextArea value={description} onChange={event => setDescription(event.target.value)} /></Form.Item></>}{review?.action === 'handover' && <><Form.Item label="未完成事项（每行一项）" required><Input.TextArea aria-label="未完成事项" value={pending} onChange={event => setPending(event.target.value)} /></Form.Item><Form.Item label="本次已阅依据"><Checkbox.Group value={evidence.map(item => `${item.kind}:${item.id}`)} onChange={values => setEvidence(evidenceChoices.filter(item => values.includes(`${item.kind}:${item.id}`)))} options={evidenceChoices.map(item => ({ value: `${item.kind}:${item.id}`, label: `${item.kind} / ${item.id} / v${String(item.version)}` }))} /></Form.Item></>}<Form.Item label="工单变更理由" required><Input.TextArea aria-label="工单变更理由" value={reason} onChange={event => setReason(event.target.value)} /></Form.Item></Form></Modal></>;
}
